<?php
$inc_datei_array=array(
   "inc_modul_top.php",
   "head_include.inc.php",
   "inc_body.php",
	 "inc_titelblock.php",
	 "submenu1.php",
	 "back.php",
	 "testform.tpl",
	 "test_person_search.php"
	 );
?>	 