<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
require('./roots.php');
require($root_path.'/include/inc_environment_global.php');
require_once($root_path.'include/inc_vars_resolve.php');
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<head>
<title>Créditos</title>
</head>
<body onLoad="if(window.focus) window.focus()">
<font face="verdana,arial" size=6 color="#0000ff">Créditos</fonts>
<hr>

<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
            <P><img src="../../fotos/credits/daniel_zilli.jpg"  border=0  align=right vspace=10>
			<b>
			O tradução brasileira do CARE 2002 e www.care2x.com foi feito por Daniel Zilli.
			</b><p>
			 Daniel Zilli é natural de Passo Fundo estado do Rio Grande do Sul - Brasil. Possui formação técnica em Engenharia de Software e está concluindo sua graduação em Sistemas de Informação. Com experiência há mais de 10 anos em informática, desenvolveu uma metodologia para trabalhar não só o lado tecnológico, mas também o lado humano das organizações.
<p>
Daniel é sócio-diretor da Lec Tecnologia, empresa especializada em consultoria de software livre, produtos para ensino Linux e segurança de informação. 
			
			<P><a href="mailto:danielz@cco.matrix.com.br"><u>Daniel Zilli pode ser contatado aqui. </u></a>
</TD></TR></TBODY></TABLE>

<hr>

<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../fotos/credits/giuseppe_scarpi.jpg"  width=135 height=170 border=0  align=right vspace=10>
			<b>A tradução italiana do CARE 2002 foi feito por Giuseppe Scarpi:</b>
			<p>
			Giuseppe Scarpi nasceu em Roma, Itália e tem 35 anos. 
<p>
Ele tem uma graduação em Engenharia Eletrônica e trabalhou para várias companhias no setor biomédico onde ele 
desenvolveu uma compreensão sobre as relações entre os mundos médicos e de informática. Ele usa e aprecia Linux e Windows, 
"<i>ambos são o resultado de um grande trabalho humano que deve ser respeitado</i>."   
  <p>
Ele decidiu unir-se ativamente ao código aberto porque:   
"<i>Tal ideal mundial só pode sobreviver se perfeitamente equilibrado. Se você levar algo, você também deveria devolver em proporção</i>."   


			<P><a href="mailto:kalbun@inwind.it"><u>Giuseppe Scarpi pode ser contatado aqui.</u></a>
</TD></TR></TBODY></TABLE>

<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
            <P><img src="../../fotos/credits/gabriele_cicala.jpg"  border=0  align=right vspace=10>
			<b>A tradução italiana do www.care2x.com foi feito por Gabriele Cicala.</b>
			
			<P><a href="mailto:gabcicala@tiscali.it"><u>Gabriele Cicala pode ser contatado aqui.</u></a>
</TD></TR></TBODY></TABLE>

<hr>

<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
            <P><img src="../../fotos/credits/agus_mr.jpg"  border=0  align=right vspace=10>
			<b>A tradução indonesia do CARE 2002 e www.care2x.com foi feito por Agus Muhammad Ramdan.</b>
			
			<P><a href="mailto:agusmr@mweb.co.id"><u>Agus M. Ramdan pode ser contatado aqui.</u></a>
</TD></TR></TBODY></TABLE>

<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../gui/img/control/default/<?php echo $lang ?>/<?php echo $lang ?>_x-blank.gif"  border=0  width=135 align=right vspace=10>
			<b>Nino Novak (DE) editou a versão germânica do www.care2x.com. </b>
<p>
Nino Novak é um pobre cowboy solitário. Ele atira mais rápido do que pensa. As vezes é um pouco inquieto. 
Ama "real gurus" e sofisticadas discussões com eles. Quer ajudar na criação de um mundo melhor. 
Alguns conhecimentos científicos e médicos (desta forma juntou-se ao projeto care2x). 


			<P><a href="mailto:nino@kflog.org"><u>Nino Novak pode ser contatado aqui.</u></a>
</TD></TR></TBODY></TABLE>

<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../gui/img/control/default/<?php echo $lang ?>/<?php echo $lang ?>_x-blank.gif"  border=0  width=135 align=right vspace=10>
<b>Patxi Gomaríz fez a tradução para o espanhol do Care 2002.</b>
<p>
Patxi Gomaríz nasceu na primavera de 1966 em Murcia, Espanha.
Sua vida e trabalho gira em torno principalmente da fotografia, sendo um especialista em fotografia para 
Oftalmologia (fundus camera). Ele é um entusiasta da internet e também faz designs de websites.
<p>
"<i>Eu acho que o código de fonte aberto é uma eficiente arma contra os efeitos negativos da economia globalizada 
especialmente em áreas fundamentais nas quais são importantes para a humanidade como a saúde. 
Por essa razão, e sinto orgulho da minha pequena contribuição para este grande projeto.</i>"

			<P><a href="mailto:pgomariz@ono.com"><u>Patxi Gomaríz pode ser contatado aqui.</u></a>
</TD></TR></TBODY></TABLE>


<hr>
<font face="verdana,arial" size=3 color="#0000ff">Mais créditos</font>
<font face="verdana,arial" size=1 > (em ordem alfabética)</font>

<table border=0 cellspacing=1 cellpadding=1>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Agus M. Ramdan (ID)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Revisão de código, care2x.com CMS</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Daniele Frijia (DE)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Exames de segurança, consultor de php</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Luki Rustianto (ID)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Aprimoramento da segurança</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Matêj Hausenblas (FR)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Tradução para o francês</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Muhammad Panji (ID)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Tradução para a indonésia</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Nino Novak (DE)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Edição Alemã do www.care2x.com</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Patxi Gomaríz (ES)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Tradução para o espanhol</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Pawel Cyrta (PL)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Tradução para o polonês</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Prantar Deka (IN)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Módulo de faturamento genérico</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Roberto Nanucci (IT)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;care2x.it mirror site</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Simone Aveotti (IT)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Tradução para o italiano</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Thomas Wiedmann (DE)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Testando, debugging, validação do scripts</font></td>
  </tr>
</table>

<font face="verdana,arial" size=1>Nota: Esta é uma lista parcial. Os créditos adicionais estão vindo.</font>
</body>
</html>
