<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
$lang='en';
define('LANG_FILE','');
define('NO_CHAIN',1);
require_once('../include/inc_front_chain_lang.php');

if(!isset($old_db_name) || !$old_db_name) 
{
   $error='link';
}

if($dbhost=='') $dbhost='localhost';
if($dbusername=='') $dbusername='httpd';

$dbname=$old_db_name;

$error='';

require('install_db_makelink.php');

if($link&&$DBLink_OK) 
{	

    $all_table=mysql_list_tables($old_db_name,$link);
	
	$i=0;
	
	while($i < mysql_num_rows($all_table))
	{
	    $tablename=mysql_tablename($all_table,$i);
		$i++;
		
		if(eregi('icd10',$tablename) || eregi('ops30', $tablename))
		{
		   continue;
		}
		else
		{
		   mysql_query('DROP TABLE '.$tablename, $link);
		}
	}
	         
	 $result='table_removed'; 

}
else
{
   $error='link';
}
?>

<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<head>
<title></title>
<meta name="Description" content="">
<meta name="Keywords" content="">
<meta name="Author" content="Lorilla Bong">
<meta name="Generator" content="AceHTML 4 Freeware">
</head>
<body bgcolor=#99ccff>

<center>
<font face="Verdana, Arial" size=5 color=#800000>
<p>
Care 2002 beta version 1.0.03 <p> Installation<p>
Step 4
</font>
<p>

<img <?php echo createMascot('../','mascot1_r.gif','0','middle') ?>>

<font face="Verdana" color=#000080><b>
<?php

 if($error=='link') 
{

echo 'The database could not be found or a link to it could not be created. <p>
You have entered the following information:<p>';

?></b>

<table border=0>
  <tr>
    <td align="right"><font size=2 face="verdana,arial">Old database name: </font></td>
    <td><font size=2 face="verdana,arial"><?php echo $old_db_name ?></td>
  </tr>
  <tr>
    <td align="right"><font size=2 face="verdana,arial">Host name: </font></td>
    <td><font size=2 face="verdana,arial"><?php echo $dbhost ?></td>
  </tr>
  <tr>
    <td align="right"><font size=2 face="verdana,arial">Username: </font></td>
    <td><font size=2 face="verdana,arial"><?php echo $dbusername ?></td>
  </tr>
  <tr>
    <td align="right"><font size=2 face="verdana,arial">Password: </font></td>
    <td><font size=2 face="verdana,arial"><?php echo $dbpassword ?></td>
  </tr>
</table>


Please go back to the previous step and enter the correct data
</font>
<form action="install_a1.php" method="post">
<input type="submit" value="Go back">

</form>

<?php
}
elseif($error=='')
{
   switch($result)
   {
     
	case 'table_removed':  echo 'The tables are now removed except the ICD and OPS tables. <br>You can now proceed to create the
	                                   new database tables.<br> Please click the button to proceed. ';
?>

<form action="install_db_create_1.php" method="post">
<a href="install_a1.php"><input type="button" value="<< Go back to previous step" onClick="javascript:window.location.replace('install_a1.php')"></a> <input type="submit" value="Proceed to next step >>">
<input type="hidden" name="mode" value="<?php echo 's5' ?>">
<input type="hidden" name="step" value="<?php echo $step + 1 ?>">
<input type="hidden" name="dbusername" value="<?php echo $dbusername ?>">
<input type="hidden" name="dbhost" value="<?php echo $dbhost?>">
<input type="hidden" name="dbpassword" value="<?php echo $dbpassword ?>">
<input type="hidden" name="dbname" value="<?php echo $old_db_name ?>">
<input type="hidden" name="create" value="no_drg">

</form>
 
<?php  
									   break;
    }
 }
    
					

?>
</center>

</body>
</html>
