<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
$lang='en';
define('LANG_FILE','');
define('NO_CHAIN',1);
require_once('../include/inc_front_chain_lang.php');
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<head>
<title></title>
<meta name="Description" content="">
<meta name="Keywords" content="">
<meta name="Author" content="Lorilla Bong">
<meta name="Generator" content="AceHTML 4 Freeware">

<script language="javascript">
<!-- Script Begin

function chkDBName(d) {

if(d.old_db_name.value =='')  
{
   alert('Please enter a name for the database');
   d.old_db_name.focus();
   return false;
 }
 else
 {
    return true;
  }

}
//  Script End -->
</script>

</head>
<body bgcolor=#99ccff>

<center>
<font face="Verdana, Arial" size=5 color=#800000>
<?php if(!isset($mode) || !$mode)
{
?>
<font size=6><b>Welcome to </b></font>
<?php
}
?>
<p>
Care 2002 beta version 1.0.03 <p> Installation<p>
Step 3

</font>
<p>

<img <?php echo createMascot('../','mascot1_r.gif','0','middle') ?>>


<font face="Verdana, Arial" color=#000080>I am going to remove the old database of Care 2002. <p>
Please enter the name of the old database<p>


<form action="install_db_remove_old_2.php" method="post" onSubmit="return chkDBName(this)">

<table border=0>
  <tr>
    <td align="right"><font size=2 face="verdana,arial">Database name: </font><p>&nbsp;</td>
    <td><input type="text" name="old_db_name" size=30 maxlength=40><p>&nbsp;</td>
  </tr>
  <tr>
    <td colspan=2><font size=1 face="verdana,arial" color="#000080">If you use default values, leave the values below unchanged.</font></td>
  </tr>
  <tr>
    <td align="right"><font size=2 face="verdana,arial">Database host name: </font></td>
    <td><input type="text" name="dbhost" size=30 maxlength=40 value="localhost"></td>
  </tr>
  <tr>
    <td align="right"><font size=2 face="verdana,arial">Database username: </font></td>
    <td><input type="text" name="dbusername" size=30 maxlength=40 value="httpd"></td>
  </tr>
  <tr>
    <td align="right"><font size=2 face="verdana,arial">Database password: </font></td>
    <td><input type="password" name="dbpassword" size=30 maxlength=40 value=""></td>
  </tr>
</table>

<p>
and press the  button.<p></font>
<p><br>
<a href="install_a.php">
<input type="button" value="<< Go back to previous step"  onClick="javascript:window.location.replace('install_a.php')"></a>
<input type="submit" value="Go ahead please >>">
 
</font>
<input type="hidden" name="remove" value="<?php echo $remove ?>">
<input type="hidden" name="mode" value="<?php echo $mode ?>">

</form>





</center>

</body>
</html>
