<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
$lang='en';
define('LANG_FILE','');
define('NO_CHAIN',1);
require_once('../include/inc_front_chain_lang.php');

$error='';

   /* If the db info are empty, assume default values */
   
    if($dbhost=='') $dbhost='localhost';
    if($dbusername=='') $dbusername='httpd';
    if(!$dbpassword) $dbpassword='';

	if(!isset($dbname)) $dbname='';
	
if($dbname!='')
{

   
    require('install_db_makelink.php');

    if($link) 
    {	
	
	   /* Check first if the db is existing */
	       $all_table=mysql_list_tables($dbname,$link);
	
	      $i=0;
	
	      while($i < mysql_num_rows($all_table))
	     {
	           $tablename=mysql_tablename($all_table,$i);
		       $i++;
		
		       if(!strcasecmp($dbname,$tablename) )
		      {
			  
			     $error='no_dbcreation';
				 echo $error;
				 break;
			  }
	    }
		
		if($error=='')
		{
               /* Load the sql batch query function */

	           include_once('include/install_db_query.php');

	            /* Create all tables and the ICD-OPS data */
		        $result=createAll($dbname);

		        if($result=='error_dbcreation') $error='no_dbcreation';
		 }

			 
    }
     else
    {
       $error='no_link';
    }
}
else
{
   
   $error='no_dbname';
}
?>

<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<head>
<title></title>
<meta name="Description" content="">
<meta name="Keywords" content="">
<meta name="Author" content="Lorilla Bong">
<meta name="Generator" content="AceHTML 4 Freeware">



<script language="javascript">
<!-- Script Begin
function chkForm(d) {

if((d.name.value =='') || (d.login_id.value =='') || (d.password.value =='') )
{
   alert('Some information are missing. Please enter the complete information.');
   return false;
 }
 else
 {
    return true;
  }

}

function chkDBName(d) {

if(d.dbname.value == '')  
{
   alert('Please enter a name for the database');
   d.dbname.focus();
   return false;
 }
 else
 {
    return true;
  }

}
//  Script End -->
</script>
</head>
<body bgcolor=#99ccff>



<center>


<font face="Verdana, Arial" size=4 color=#800000>
<p>


Care 2002 beta version 1.0.03 <p> Installation<p>
Step <?php if(!$dbname) echo 2;
            elseif($error=='') echo 4; else echo 3; ?>

</font>
<p>

<img <?php echo createMascot('../','mascot1_r.gif','0','middle') ?>>


<font face="Verdana" color=#000080><b>

<?php

 if($error!='') 
{

if($error=='no_dbname') echo 'Please enter the name for the new database. ';
  elseif($error=='no_link') echo 'The link to the database server could not be established. <br>The access information could be erroneous.
            Please enter the correct information.
           <br><font size=2> </b>You have previously entered the following access information.<b></font> ';
    else  echo 'The database creation failed. It is probably already existing.<br>
            Please use a different name for the database.
           <br><font size=2> </b>You have previously entered the following information.<b></font> ';

?></b>
<p>
<form action="install_db_create_mask.php" method="post" onSubmit="return chkDBName(this)">

<table border=0>
  <tr>
    <td align="right"><font size=2 face="verdana,arial">Database name: </font><p>&nbsp;</td>
    <td><input type="text" name="dbname" size=30 maxlength=40 value="<?php echo $dbname ?>"><p>&nbsp;</td>
  </tr>
  
  <?php
   if($error=='no_dbname')
   {
   ?>
  <tr>
    <td colspan=2><font size=1 face="verdana,arial" color="#000080">If you use default values, leave the values below unchanged.</font></td>
  </tr>
  <?php
  }
  ?>
  <tr>
    <td align="right"><font size=2 face="verdana,arial">Database host name: </font></td>
    <td><input type="text" name="dbhost" size=30 maxlength=40 value="<?php echo $dbhost ?>"></td>
  </tr>
  <tr>
    <td align="right"><font size=2 face="verdana,arial">Database username: </font></td>
    <td><input type="text" name="dbusername" size=30 maxlength=40 value="<?php echo $dbusername ?>"></td>
  </tr>
  <tr>
    <td align="right"><font size=2 face="verdana,arial">Database password: </font></td>
    <td><input type="password" name="dbpassword" size=30 maxlength=40 value="<?php echo $dbpassword ?>"></td>
  </tr>
</table>

<p>
and press the  button.<p></font>
<p><br>
<a href="install.php">
<input type="button" value="<< Go back to previous step" onClick="javascript:window.location.replace('install.php')"></a>
<input type="submit" value="Go ahead please >>">
 
</font>
<input type="hidden" name="origin" value="path_b">

</form>




<?php
}
elseif($error=='')
{

	                                    echo 'The database is now in place.<br><font size=2>You can now create your Admin access. Please
										enter the needed information below. ';
?>

<form action="install_db_create_admin.php" method="post" onSubmit="return chkForm(this)">

<table border=0>
  <tr>
    <td><font size=2 face="verdana,arial">Normal name: </font></td>
    <td><input type="text" name="name" size=30 maxlength=40></td>
  </tr>
  <tr>
    <td><font size=2 face="verdana,arial">Admin login username: </font></td>
    <td><input type="text" name="login_id" size=30 maxlength=40></td>
  </tr>
  <tr>
    <td><font size=2 face="verdana,arial">Admin password: </font></td>
    <td><input type="text" name="password" size=30 maxlength=40></td>
  </tr>
   <tr>
    <td colspan=2>&nbsp;<br><font size=1 face="verdana,arial">If you leave the following fields empty, random keys will be automatically created.</font></td>
  </tr>
 <tr>
    <td><font size=2 face="verdana,arial">First level key: </font></td>
    <td><input type="text" name="k1" size=30 maxlength=40></td>
  </tr>
  <tr>
    <td><font size=2 face="verdana,arial">Second level key: </font></td>
    <td><input type="text" name="k2" size=30 maxlength=40></td>
  </tr>
  <tr>
    <td><font size=2 face="verdana,arial">Third level key: </font></td>
    <td><input type="text" name="k3" size=30 maxlength=40></td>
  </tr>

</table>

<p>
and press the  button.</font>
<br>
<input type="submit" value="Go ahead please >>">
 
</font>
<input type="hidden" name="remove" value="tables">
<input type="hidden" name="dbusername" value="<?php echo $dbusername ?>">
<input type="hidden" name="dbhost" value="<?php echo $dbhost?>">
<input type="hidden" name="dbpassword" value="<?php echo $dbpassword ?>">
<input type="hidden" name="dbname" value="<?php echo $dbname ?>">

</form>

</font>

<?php  

 }
    
					

?>
</center>

</body>
</html>
