<?php

error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
$lang='en';
define('LANG_FILE','');
define('NO_CHAIN',1);
require_once('../include/inc_front_chain_lang.php');

$error='';

if($dbname!='')
{

   /* If the db info are empty, assume default values */
   
    if($dbhost=='') $dbhost='localhost';
    if($dbusername=='') $dbusername='httpd';
    if(!$dbpassword) $dbpassword='';
	
	if($k1=='') $k1=uniqid('care');
 	if($k2=='') $k2=uniqid('care').$k1;
	if($k3=='') $k3=uniqid('care',true);
  

	$fp=fopen('../include/inc_init_main.php','w+');
	
	if($fp)
	{
	   fputs($fp,'<?php ');
	   fputs($fp, "\n\r");
	   fputs($fp,'$dbname=\''.$dbname.'\'; ');
	   fputs($fp, "\n\r");
	   fputs($fp,'$dbusername=\''.$dbusername.'\'; ');
	   fputs($fp, "\n\r");
	   fputs($fp,'$dbhost=\''.$dbhost.'\'; ');
	   fputs($fp, "\n\r");
	   fputs($fp,'$dbpassword=\''.$dbpassword.'\'; ');
	   fputs($fp, "\n\r");
	   fputs($fp,'$key=\''.$k1.'\'; ');
	   fputs($fp, "\n\r");
	   fputs($fp,'$key_2level=\''.$k2.'\'; ');
	   fputs($fp, "\n\r");
	   fputs($fp,'$key_login=\''.$k3.'\'; ');
	   fputs($fp, "\n\r");
	   fputs($fp,' ?>');
    
	   fclose($fp);
	   
	   require('install_db_makelink.php');

       if($link && $DBLink_OK) 
       {
	        $sql= 'INSERT INTO care_users (name, login_id, password, permission, exc, s_date, s_time, create_id, create_time) 
		           VALUES (\''.$name.'\', \''.$login_id.'\', \''.$password.'\', \'System_Admin\', 1, \''.date('Y-m-d').'\', \''.date('H:i:s').'\', \'Installation\', NULL)';	   
				   
		  if(!mysql_query($sql, $link))    $error= 'no_admin_save';
			 
		  	 
	   }  
	   else
	   {
	     $error='no_link';
	   }
	}
	else
	{
	   $error='no_file_write';
	}
	
}
else
{
   
   $error='no_dbname';
}
?>

<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<head>
<title></title>
<meta name="Description" content="">
<meta name="Keywords" content="">
<meta name="Author" content="Lorilla Bong">
<meta name="Generator" content="AceHTML 4 Freeware">



<script language="">
<!-- Script Begin
function chkForm(d) {

if((d.dbname.value =='') || (d.name.value =='') || (d.login_id.value =='') || (d.password.value =='') )
{
   alert('Some information are missing. Please enter the complete information.');
   return false;
 }
 else
 {
    return true;
  }

}
//  Script End -->
</script>
</head>
<body bgcolor=#99ccff>



<center>


<font face="Verdana, Arial" size=4 color=#800000>
<p>

Care 2002 beta version 1.0.03 <p> Installation<p>

<?php if($error=='') echo 'Finish<br>'; else echo ' Final Step<br>'; ?> 

</font>
<p>

<img <?php echo createMascot('../','mascot1_r.gif','0','middle') ?>>


<font face="Verdana" color=#000080><b>
<?php

 if($error=='') 
{
      echo 'Congratulations! You have installed Care 2002 successfully.<p>';

?>
</b>
<form action="../" >

<p><br>&nbsp;<br>
</font>
 <input type="submit" value="Start Care 2002 now >>">
</form>

<?php
}
else
{
    switch($error)
	{
	
	   case 'no_dbname' : echo 'The database name is missing. Please enter it  again...'; break;
	   case 'no_link' : echo 'A link to the mySQL server could not be established. Please check the access information again...'; break;
	   case 'no_file_write' : echo 'Saving of admin data failed.<br> Please make sure that the "include" directory and the "inc_init_main.php" script are
	                                          not write-protected...';
	}
?>

<form action="install_db_create_admin.php" method="post" onSubmit="return chkForm(this)">

<table border=0>
  <tr>
    <td><font size=2 face="verdana,arial">Database name: </font></td>
    <td><input type="text" name="dbname" size=30 maxlength=40 value="<?php echo $dbname ?>"></td>
  </tr>
  <tr>
    <td><font size=2 face="verdana,arial">Normal user's name: </font></td>
    <td><input type="text" name="name" size=30 maxlength=40 value="<?php echo $name ?>"></td>
  </tr>
  <tr>
    <td><font size=2 face="verdana,arial">Login username: </font></td>
    <td><input type="text" name="login_id" size=30 maxlength=40 value="<?php echo $login_id ?>"></td>
  </tr>
  <tr>
    <td><font size=2 face="verdana,arial">Password: </font></td>
    <td><input type="text" name="password" size=30 maxlength=40 value="<?php echo $password ?>"></td>
  </tr>
  <tr>
    <td><font size=2 face="verdana,arial">First level key: </font></td>
    <td><input type="text" name="k1" size=30 maxlength=40 value="<?php echo $k1 ?>"></td>
  </tr>
  <tr>
    <td><font size=2 face="verdana,arial">Second level key: </font></td>
    <td><input type="text" name="k2" size=30 maxlength=40 value="<?php echo $k2 ?>"></td>
  </tr>
  <tr>
    <td><font size=2 face="verdana,arial">Third level key: </font></td>
    <td><input type="text" name="k3" size=30 maxlength=40 value="<?php echo $k3 ?>"></td>
  </tr>

</table>

<p>
and press the  button.</font>
<br>
<input type="submit" value="Go ahead please >>">
 
</font>
<input type="hidden" name="remove" value="tables">
<input type="hidden" name="dbusername" value="<?php echo $dbusername ?>">
<input type="hidden" name="dbhost" value="<?php echo $dbhost?>">
<input type="hidden" name="dbpassword" value="<?php echo $dbpassword ?>">

</form>

</font>

<?php  

 }
    
					

?>
</center>

</body>
</html>
