<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
$lang='en';
define('LANG_FILE','');
define('NO_CHAIN',1);
require_once('../include/inc_front_chain_lang.php');
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<head>
<title></title>
<meta name="Description" content="">
<meta name="Keywords" content="">
<meta name="Author" content="Lorilla Bong">
<meta name="Generator" content="AceHTML 4 Freeware">
</head>
<body bgcolor=#99ccff>

<center>
<font face="Verdana, Arial" size=5 color=#800000>

<font size=6><b>Welcome to </b></font>

<p>
Care 2002 beta version 1.0.03 <p> Installation<p>
Step 1

</font>
<p>

<img <?php echo createMascot('../','mascot1_r.gif','0','middle') ?>>



<font face="Verdana, Arial" color=#000080><b> Please choose  one of the following steps that you want me to do next.</b></font>
<p>
<table border=0>
  <tr>
    <td>
<font face="Verdana, Arial" size=3>
<img <?php echo createComIcon('../','bul_arrowgrnlrg.gif','0','absmiddle') ?>> <a href="install_a.php">Remove an existing old database of Care 2002</a> <br>
<font size=2>( Or to remove only tables from an existing database of Care 2002 except the ICD/OPS tables.<br>This will avoid the very long
process of generating new ICD/OPS data [10 minutes] ).</font>
<p>
<img <?php echo createComIcon('../','bul_arrowgrnlrg.gif','0','absmiddle') ?>> <a href="install_db_create_b.php">Go ahead and create a new database</a> <p>
<img <?php echo createComIcon('../','dwnarrowgrnlrg.gif','0','absmiddle') ?>> <a href="../blank.htm">Cancel this installation process now</a><p>
	</font>
	</td>
  </tr>
</table>




</center>

</body>
</html>
