<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
$lang='en';
define('LANG_FILE','');
define('NO_CHAIN',1);
require_once('../include/inc_front_chain_lang.php');
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<head>
<title></title>
<meta name="Description" content="">
<meta name="Keywords" content="">
<meta name="Author" content="Lorilla Bong">
<meta name="Generator" content="AceHTML 4 Freeware">
</head>
<body bgcolor=#99ccff>

<center>
<font face="Verdana, Arial" size=5 color=#800000>

<p>
Care 2002 beta version 1.0.03 <p> Installation<p>
Step 2 

</font>
<p>

<img <?php echo createMascot('../','mascot1_r.gif','0','middle') ?>>



<font face="Verdana, Arial" color=#000080><b>In removing the datase I could do one of the two possible options. <p> Please choose the right one</b></font>
<p>
<table border=0>
  <tr>
    <td>
<font face="Verdana, Arial" size=3>
<img <?php echo createComIcon('../','bul_arrowgrnlrg.gif','0','absmiddle') ?>> <a href="install_a1.php?mode=s3&step=3">Remove all the tables except the ICD and OPS tables and retain the database.</a> <p>
<img <?php echo createComIcon('../','bul_arrowgrnlrg.gif','0','absmiddle') ?>> <a href="install_a2.php?mode=s4&remove_all=1&step=3">Remove everything. I want to create a completely new database.</a> <p>
<img <?php echo createComIcon('../','l-arrowgrnlrg.gif','0','absmiddle') ?>> <a href="install.php?">Go back to previous step.</a> <p>
<img <?php echo createComIcon('../','dwnarrowgrnlrg.gif','0','absmiddle') ?>> <a href="../blank.htm">Cancel this installation process now</a><p>
	</font>
	</td>
  </tr>
</table>



</center>

</body>
</html>
