<?
$allow_area['admit']=array("admit","all","System_Admin");
$allow_area['cafe']=array("cafe","all","System_Admin");
$allow_area['medocs']=array("medocs","all","System_Admin");
$allow_area['phonedir']=array("all","System_Admin");
$allow_area['doctors']=array("doc","all","System_Admin");
$allow_area['wards']=array("wards","all","System_Admin");
$allow_area['op_room']=array("op_room","all_op_room","doc_op","duty_op","all","System_Admin");
$allow_area['tech']=array("tech","all","System_Admin");
$allow_area['lab_r']=array("lab_read","all","System_Admin");
$allow_area['lab_w']=array("lab_read","lab_write","all","System_Admin");
$allow_area['radio']=array("radio","doc","doc_op","all","System_Admin");
$allow_area['pharma']=array("pharma","all","System_Admin");
$allow_area['depot']=array("meddepot","all","System_Admin");
$allow_area['edp']=array("System_Admin");
$allow_area['news']=array("news","all","System_Admin");
$allow_area['op_docs']=array("doc_op","all","System_Admin");
$allow_area['duty_op']=array("duty_op","all","System_Admin");
$allow_area['cafenews']=array("cafenews","news","all","System_Admin");
?>
