<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 02.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>
<meta name="Description" content="">
<meta name="Keywords" content="">
<meta name="Author" content="Lorilla Bong">
<meta name="Generator" content="AceHTML 4 Freeware">
</head>

<frameset rows="15%,*">
  <frame name="DIRFRAME" src="fotolab-dir-select.php?sid=<?=$ck_sid ?>">
  <frameset rows="31%,*">
    <frame name="THUMBNAILSFRAME" src="fotolab-thumbnails.php">
    <frame name="PREVIEWFRAME" src="fotolab-preview.php">
  </frameset>
<noframes>
<body>


</body>
</noframes>
</frameset>
</html>
