<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 08.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>

<script language="javascript">
<!-- 

function sendnum(d)
{
	d.material_nr.select();
	window.parent.OPMLISTFRAME.location.replace('op-material-list.php?sid=<?=$ck_sid ?>&mode=search&material_nr='+d.material_nr.value);
	return false;
}
// -->
</script>


</head>
<body onLoad="document.mat_input.material_nr.focus();document.mat_input.material_nr.select()" onFocus="document.mat_input.material_nr.select()" >
<form name="mat_input" onSubmit="return sendnum(this)">
<font face="Verdana, Arial" size=2 color=#800000>
Artikelnummer:<br>
<input type="text" name="material_nr" size=20 maxlength=40 onFocus="this.select()" ><br>
<input type="submit" value="OK">
</font>
</form><p>
<hr>
<p>

<a href="javascript:window.parent.location.replace('oplogmain.php?sid=<?  print "$ck_sid&patnum=$patnum&dept=$dept&saal=$saal&pday=$pday&pmonth=$pmonth&pyear=$pyear"; ?>')"><img src="../img/manfldr.gif" width=35 height=35 border=0><br> Logbuch einblenden
</a>
</body>
</html>
