<?
if(($sid==NULL)||($sid!=$ck_sid)) { header("location:invalid-access-warning.php"); exit;}

$thisfile="radiolog-xray-diagnosis.php";

if($mode=="search")
{
include("../req/db_dbp.php");

$link=mysql_connect($dbhost,$dbusername,$dbpassword);
 if ($link)
 {
	if(mysql_select_db($dbname,$link)) 
	{	
	// get orig data

	  		$dbtable="pharma_products_main";
		 	$sql="SELECT bestellnum,artikelnum,artikelname,industrynum,generic,description FROM $dbtable WHERE artikelnum LIKE '$material_nr%'";
			
			if(!empty($patnum))
				if(is_numeric($patnum)) $patnum=(int) $patnum; else $patnum="";
					

			//print $sql;
				if($ergebnis=mysql_query($sql,$link))
       			{
					$rows=0;
					if( $pdata=mysql_fetch_array($ergebnis)) $rows++;
					if($rows)
					{
						mysql_data_seek($ergebnis,0); //reset the variable
						//$datafound=1;
						//$pdata=mysql_fetch_array($ergebnis);
						//print $sql."<br>";
						//print $rows;
					}
					//else print "<p>".$sql."<p>Multiple entries found pls notify the edv."; 
				}
				else print "<p>".$sql."<p>Das Lesen  aus der Datenbank $dbtable ist gescheitert."; 

	}else print "$db_table_noselect $sql<br>";
	mysql_close($link);
  } else { print "$db_noconnect $sql<br>"; }

}

?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 02.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>

 <style type="text/css" name="s2">
.v12{ font-family:verdana,arial; color:#000000; font-size:12;}
.v12b{ font-family:verdana,arial; color:#cc0000; font-size:12;}
</style>

<script language="javascript">
<!-- 

function demopreview(x)
{
	window.parent.PREVIEWFRAME.location.replace('radiolog-xray-display-film.php?sid=<?=$ck_sid ?>&mode=preview');
	window.parent.DIAGNOSISFRAME.location.replace('radiolog-xray-diagnosis.php?sid=<?=$ck_sid ?>&mode=preview');
	document.plist.xray_pic[x].checked=true;
}

function popinfo(b)
{
	urlholder="products-bestellkatalog-popinfo.php?sid=<? print $ck_sid; ?>&keyword="+b+"&mode=search&cat=pharma";
	ordercatwin=window.open(urlholder,"ordercat","width=850,height=550,menubar=no,resizable=yes,scrollbars=yes");
	}
// -->
</script>
</head>
<body leftmargin=0 marginwidth=0>


<? 
if($rows)
{
print'
<form name="plist">
<table border=0 cellpadding=0 cellspacing=0 width="100%">
  <tr>
    <td class="v12b"><b>&nbsp;Art.Nr.</b></td>
    <td class="v12b"><b>Art.name</b></td>
    <td class="v12b"><b></b></td>
    <td class="v12b"><b>Generic</b></td>
    <td class="v12b"><b>Zul.Nr.</b></td>
    <td class="v12b"><b>Anzahl</b></td>
    <td class="v12b"><b>&nbsp;</b></td>
  </tr>
   <tr>
    <td colspan=7 bgcolor="#0000ff"></td>
  </tr>

';
	$i=0;
	while($pdata=mysql_fetch_array($ergebnis))
	{
		print'
 <tr>
    <td class="v12">&nbsp;'.$pdata[artikelnum].'&nbsp;</td>
    <td class="v12">&nbsp;'.$pdata[artikelname].'&nbsp;</td>
    <td class="v12">&nbsp;<a href="javascript:popinfo('.$pdata[bestellnum].')"><img src="../img/info3.gif" width=16 height=16 border=0></a>&nbsp;</td>
    <td class="v12">&nbsp;'.$pdata[generic].'&nbsp;</td>
    <td class="v12">&nbsp;'.$pdata[industrynum].'&nbsp;</td>
    <td class="v12">&nbsp;<input type="text" name="pcs" size=1 maxlength=2 value="1">
                          &nbsp;</td>
    <td class="v12">&nbsp;<a href="javascript:delete_item()" title="Artikel aus der Lister entfernen"><img src="../img/delete2.gif" width=20 height=20 border=0></a>&nbsp;</td>
  </tr>
  <tr>
    <td colspan=7 bgcolor="#0000ff"></td>
  </tr>';
  	$i++;
  }
  
  print '
</table>
<input type="submit" value="Änderung speichern">

</form>  
  ';
}
?>


</body>
</html>
