<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 25.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>
</head>
<body alink="#0000ff" vlink="#0000ff" link="#0000ff">
<font face="Arial" color="#cc0000" size=3><b>Ajuda</b></font><p>
<font face="Verdana, Arial" size=2><b>
<a href="../main/help-info.php" target="HELPINFOFRAME">Passos iniciais</a><br>
<!--<a href="../help/en/help_en_contents.php" target="HELPINFOFRAME">Conteúdo</a><br>
 <a href="#" target="HELPINFOFRAME">Índice</a><br>
<a href="#" target="HELPINFOFRAME">Pesquisa</a><br>
<a href="#" target="HELPINFOFRAME">Dicas e Truques</a><br>
<a href="#" target="HELPINFOFRAME">Introduções</a></b>
 --><p>
<a href="http://care2x.net/docswiki/index.php?UM - English" target="HELPINFOFRAME"> Manual Online</a></b>

</font>

</body>
</html>
