<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
/**
* CARE 2002 Integrated Hospital Information System beta 1.0.03 - 2002-10-26
* GNU General Public License
* Copyright 2002 Elpidio Latorilla
* elpidio@latorilla.com
*
* See the file "copy_notice.txt" for the licence notice
*/
define('LANG_FILE','editor.php');
$local_user='ck_cafenews_user';
require_once('../include/inc_front_chain_lang.php');
require_once('../include/inc_config_color.php');

if($groupopt)
switch($groupopt)
{
	case "newgroup":	header("Location: cafenews-edit-price-newgroup.php?sid=$sid&lang=$lang");
						break;
	case "set_currency":	header("Location: cafenews-edit-price-currency-set.php?sid=$sid&lang=$lang");
						break;
	default: header("Location: cafenews-edit-price.php?sid=$sid&groupname=$groupopt&lang=$lang");break; 
}

$breakfile="cafenews.php?sid=".$sid."&lang=".$lang;

$dbtable="care_cafe_prices";

/* Establish db connection */
require('../include/inc_db_makelink.php');
 if ($link&&$DBLink_OK)
 {
		 	$sql="SELECT article FROM $dbtable WHERE description='group'";	
			
            if(defined('LANG_DEPENDENT') && (LANG_DEPENDENT==1))
            {
	            $sql.="' AND lang='".$lang."'";
            }
			
			if($ergebnis=mysql_query($sql,$link))
       		{
				$rows=0;
				while( $ginfo=mysql_fetch_array($ergebnis)) $rows++;
				if($rows)
				{
					mysql_data_seek($ergebnis,0);
				}
			}
				else echo "<p>".$sql."<p>$LDDbNoRead"; 

  } else { echo "$LDDbNoLink<br> $sql<br>"; }


?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 21.12.2001 -->
<head>
<?php echo setCharSet(); ?>
<title></title>

<?php if($rows) : ?>
<script language="javascript">
function chkForm(d)
{
	var opt=<?php echo $rows+3 ?>;
	if(opt==2)
	{
		if((d.groupopt[0].checked)||(d.groupopt[1].checked)) return true;
		else return false;
	}
	else
	{
		for(i=0;i<opt;i++)
		{
			if(d.groupopt[i].checked) return true;
		}
		return false;
	}
}
</script>
<?php endif ?>

<?php if($cfg['dhtml']) include("../include/inc_css_a_hilitebu.php"); ?>

</head>
<body>
<FONT  SIZE=8 COLOR="#cc6600" FACE="verdana,Arial">
<a href="javascript:editcafe()"><img <?php echo createComIcon('../','basket.gif','0') ?>></a> <b><?php echo $LDCafePrices ?></b></FONT>
<hr>
<form name="selectform" action="cafenews-edit-price-select.php" <?php if($rows) echo 'onSubmit="return chkForm(this)"'; ?>>
<table border=0>
  <tr>
    <td><img <?php echo createMascot('../','mascot1_r.gif','0') ?>></td>
    <td colspan=2><FONT  SIZE=4 COLOR="#000066" FACE="verdana,Arial">
<?php if ($rows) : ?>
			<?php echo $LDMarkGroup ?>
<?php else : ?>
			<?php echo $LDCreateGroupPrompt ?>
<?php endif ?>
	</td>
  </tr>
<?php if($rows)
{
	echo '
  <tr>
    <td>&nbsp;</td>
    <td bgcolor="ccffff" colspan=2><FONT FACE="verdana,Arial"><p><br>';
	for($i=0;$i<$rows;$i++)
	{
		$ginfo=mysql_fetch_array($ergebnis);
		echo '
		<input type="radio" name="groupopt" value="'.$ginfo['article'].'"> 
		<a href="#" onClick="document.selectform.groupopt['.$i.'].checked=true"> '.$ginfo['article'].'</a><br>';
	}
	echo '
  <p></td>
  </tr>
  <tr>
    <td >&nbsp;</td>
    <td colspan=2><FONT  SIZE=4 COLOR="#000066" FACE="verdana,Arial">'.$LDOr.'...</td>
  </tr>
	';
}
 ?>

    <td>&nbsp;</td>
    <td bgcolor="ccffff" colspan=2><FONT FACE="verdana,Arial"><p><br>
		<input type="radio" name="groupopt" value="newgroup" <?php if (!$rows) echo "checked"; ?>> 
		<a href="#" <?php if($rows) echo 'onClick="document.selectform.groupopt['.$i.'].checked=true"';?>><?php echo $LDCreateGroup ?></a><br><p>
  </td>
  </tr>
  <tr>
    <td >&nbsp;</td>
    <td colspan=2><FONT  SIZE=4 COLOR="#000066" FACE="verdana,Arial"><?php echo $LDOr ?>...</td>
  </tr>
    <td>&nbsp;</td>
    <td bgcolor="ccffff" colspan=2><p><br><FONT FACE="verdana,Arial">
		<input type="radio" name="groupopt" value="set_currency" <?php if (!$rows) echo "checked"; ?>> 
		<a href="#" <?php $i++; if($rows) echo 'onClick="document.selectform.groupopt['.$i.'].checked=true"';?>><?php echo $LDSetCurrency ?></a>
		<p>
 </td>
  </tr>
  <tr>
    <td>
	<a href="javascript:window.history.back()"><img <?php echo createLDImgSrc('../','back2.gif','0') ?>></a>
	</td>
    <td >
<input type="image" <?php echo createLDImgSrc('../','continue.gif','0') ?>>
  </td>
    <td>
	<a href="<?php echo $breakfile ?>"><img <?php echo createLDImgSrc('../','cancel.gif','0') ?>></a>
  </td>
  </tr>
  
</table>
<input type="hidden" name="sid" value="<?php echo $sid ?>">
<input type="hidden" name="lang" value="<?php echo $lang ?>">
</form></body>
</html>
