<?
if(!$lang)
	if(!$ck_language) include("../chklang.php");
		else $lang=$ck_language;
if (!$sid||($sid!=$ck_sid)) {header("Location:../language/".$lang."/lang_".$lang."_invalid-access-warning.php"); exit;}; 

require("../language/".$lang."/lang_".$lang."_editor.php");
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 21.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>

<script language="javascript">
function chkForm(d)
{
	if((d.week[0].checked)||(d.week[1].checked)||(d.week[2].checked)) return true;
		else return false;
}
</script>

</head>
<body>
<FONT  SIZE=6 COLOR="#cc6600" FACE="verdana,Arial">
<img src="../img/basket.gif" width=74 height=70 border=0><b><?=$LDCafeMenu ?></b></FONT>
<hr>
<form name="selectform" action="cafenews-edit-menu.php" onSubmit="return chkForm(this)">
<table border=0>
  <tr>
    <td><img src="../img/catr.gif" width=88 height=80 border=0></td>
    <td colspan=2><FONT FACE="verdana,Arial"><FONT  SIZE=5 COLOR="#000066" FACE="verdana,Arial">
		<?=$LDMarkWeek ?></font><p>
			<font size=2><?=$LDClkContinue ?></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td bgcolor="ccffff" colspan=2><FONT FACE="verdana,Arial"><p><br>
		<input type="radio" name="week" value="1"> <a href="#" onClick="document.selectform.week[0].checked=true"><?=$LDThisWeek ?></a><br>
    	<input type="radio" name="week" value="2"> <a href="#" onClick="document.selectform.week[1].checked=true"><?=$LDNextWeek ?></a><br>
    	<input type="radio" name="week" value="3"> <a href="#" onClick="document.selectform.week[2].checked=true"><?=$LD3rdWeek ?></a><br><p>
  </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><p><br>
		<input type="button" value="<?=$LDBackBut ?>" onClick="window.history.back()">&nbsp;&nbsp;&nbsp;
        <input type="button" value="<?=$LDCancelBut ?>" onClick="window.location.replace('cafenews.php?sid=<?="$ck_sid&lang=$lang" ?>')"></td>
    <td align=right><p><br><FONT FACE="verdana,Arial">
		<input type="submit" value="<?=$LDContinueBut ?>">
  </td>
  </tr>
</table>
<input type="hidden" name="sid" value="<?=$ck_sid ?>">
<input type="hidden" name="lang" value="<?=$lang ?>">
</form></body>
</html>
