<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
/**
* CARE 2002 Integrated Hospital Information System beta 1.0.03 - 2002-10-26
* GNU General Public License
* Copyright 2002 Elpidio Latorilla
* elpidio@latorilla.com
*
* See the file "copy_notice.txt" for the licence notice
*/
define('LANG_FILE','editor.php');
$local_user='ck_cafenews_user';
require_once('../include/inc_front_chain_lang.php');
require_once('../include/inc_config_color.php');

$breakfile="startframe.php?sid=".$sid."&lang=".$lang;

switch($cafeopt)
{
	case "price":	header("Location: cafenews-edit-price-select.php?sid=$sid&cafeopt=price&lang=$lang&title=$title");
						break;
	case "menu":	header("Location: cafenews-edit-menu-select-week.php?sid=$sid&lang=$lang&title=$title");
						break;
	case "news":	header("Location: cafenews-edit-select-art.php?sid=$sid&lang=$lang&title=$title");
						break;
}
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 21.12.2001 -->
<head>
<?php echo setCharSet(); ?>
<title></title>

<script language="javascript">
function chkForm(d)
{
	if((d.cafeopt[0].checked)||(d.cafeopt[1].checked)||(d.cafeopt[2].checked)) return true;
		else return false;
}
</script>

<?php if($cfg['dhtml']) include("../include/inc_css_a_hilitebu.php"); ?>

</head>
<body>
<FONT  SIZE=8 COLOR="#cc6600" FACE="verdana,Arial">
<img <?php echo createComIcon('../','basket.gif','0') ?>><b><?php echo $LDCafeNews ?></b></FONT>
<hr>
<form name="selectform" action="cafenews-edit-select.php" onSubmit="return chkForm(this)" method="post">
<table border=0>
  <tr>
    <td><img <?php echo createMascot('../','mascot1_r.gif','0') ?>></td>
    <td colspan=2><FONT FACE="verdana,Arial"><FONT  SIZE=5 COLOR="#000066" FACE="verdana,Arial"><?php echo $LDWhatToDo ?></font><p>
			<font size=2><?php echo $LDPlsMarkSelection ?></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td bgcolor="ccffff" colspan=2><FONT FACE="verdana,Arial"><p><br>
		<input type="radio" name="cafeopt" value="menu"> <a href="#" onClick="document.selectform.cafeopt[0].checked=true"><?php echo $LDMenuEdit ?></a><br>
    	<input type="radio" name="cafeopt" value="price"> <a href="#" onClick="document.selectform.cafeopt[1].checked=true"><?php echo $LDPriceEdit ?></a><br>
    	<input type="radio" name="cafeopt" value="news"> <a href="#" onClick="document.selectform.cafeopt[2].checked=true"><?php echo $LDNewsEdit ?></a><br><p>
  </td>
  </tr>

  <tr>
    <td><p><br>
	<a href="cafenews.php?sid=<?php echo "$sid&lang=$lang" ?>"><img <?php echo createLDImgSrc('../','back2.gif','0') ?>></a>
	</td>
    <td><p><br>
<input type="image" <?php echo createLDImgSrc('../','continue.gif','0') ?>>
        </td>
    <td align=right><p><br><FONT FACE="verdana,Arial">
  &nbsp;</td>
  </tr>
</table>
<input type="hidden" name="sid" value="<?php echo $sid ?>">
<input type="hidden" name="title" value="<?php echo strtr($LDCafeNews," ","+") ?>">
<input type="hidden" name="lang" value="<?php echo $lang ?>">
</form></body>
</html>
