<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
/**
* CARE 2002 Integrated Hospital Information System beta 1.0.03 - 2002-10-26
* GNU General Public License
* Copyright 2002 Elpidio Latorilla
* elpidio@latorilla.com
*
* See the file "copy_notice.txt" for the licence notice
*/
define('LANG_FILE','editor.php');
$local_user='ck_cafenews_user';
require_once('../include/inc_front_chain_lang.php');
require_once('../include/inc_config_color.php');

$breakfile="cafenews.php?sid=".$sid."&lang=".$lang;
$back2file="cafenews-edit-price-select.php?sid=".$sid."&lang=".$lang;
$thisfile="cafenews-edit-price-currency-set.php";

/**
* Load the db routine
*/
require("../include/inc_currency_set.php");
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 21.12.2001 -->
<head>
<?php echo setCharSet(); ?>
<title></title>

<?php if($rows) : ?>
<script language="javascript" src="../js/check_currency_same_item.js">
</script>
<?php endif ?>

<?php if($cfg['dhtml']) include("../include/inc_css_a_hilitebu.php"); ?>

</head>
<body>
<FONT  SIZE=8 COLOR="#cc6600" FACE="verdana,Arial">
<a href="javascript:editcafe()"><img <?php echo createComIcon('../','basket.gif','0') ?>></a> <b><?php echo $LDCafePrices ?></b></FONT>
<hr>
<?php 
/**
* Create the GUI body
*/
$bottomlink="edv-main-pass.php?sid=".$sid."&lang=".$lang."&target=currency_admin"; 
$bottomlink_txt=$LDClk2AddCurrency;
require("../include/inc_currency_set_gui.php"); 
?>
</body>
</html>
