<?
if(!$lang)
	if(!$ck_language) include("../chklang.php");
		else $lang=$ck_language;
if(!$sid||($sid!=$ck_sid)) { header("location:../language/$lang/lang_".$lang."_invalid-access-warning.php"); exit;}

require("../language/".$lang."/lang_".$lang."_editor.php");

switch($cafeopt)
{
	case "price":	header("Location: cafenews-edit-price-select.php?sid=$ck_sid&cafeopt=price&lang=$lang&title=$title");
						break;
	case "menu":	header("Location: cafenews-edit-menu-select-week.php?sid=$ck_sid&lang=$lang&title=$title");
						break;
	case "news":	header("Location: cafenews-edit-select-art.php?sid=$ck_sid&lang=$lang&title=$title");
						break;
}
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 21.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>

<script language="javascript">
function chkForm(d)
{
	if((d.cafeopt[0].checked)||(d.cafeopt[1].checked)||(d.cafeopt[2].checked)) return true;
		else return false;
}
</script>

</head>
<body>
<FONT  SIZE=8 COLOR="#cc6600" FACE="verdana,Arial">
<img src="../img/basket.gif" width=74 height=70 border=0><b><?=$LDCafeNews ?></b></FONT>
<hr>
<form name="selectform" action="cafenews-edit-select.php" onSubmit="return chkForm(this)" method="post">
<table border=0>
  <tr>
    <td><img src="../img/catr.gif" width=88 height=80 border=0></td>
    <td colspan=2><FONT FACE="verdana,Arial"><FONT  SIZE=5 COLOR="#000066" FACE="verdana,Arial"><?=$LDWhatToDo ?></font><p>
			<font size=2><?=$LDPlsMarkSelection ?></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td bgcolor="ccffff" colspan=2><FONT FACE="verdana,Arial"><p><br>
		<input type="radio" name="cafeopt" value="menu"> <a href="#" onClick="document.selectform.cafeopt[0].checked=true"><?=$LDMenuEdit ?></a><br>
    	<input type="radio" name="cafeopt" value="price"> <a href="#" onClick="document.selectform.cafeopt[1].checked=true"><?=$LDPriceEdit ?></a><br>
    	<input type="radio" name="cafeopt" value="news"> <a href="#" onClick="document.selectform.cafeopt[2].checked=true"><?=$LDNewsEdit ?></a><br><p>
  </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><p><br><input type="button" value="<?=$LDCancelBut ?>" onClick="window.location.replace('cafenews.php?sid=<?=$ck_sid ?>')">
        </td>
    <td align=right><p><br><FONT FACE="verdana,Arial">
		<input type="submit" value="<?=$LDContinueBut ?>">
  </td>
  </tr>
</table>
<input type="hidden" name="sid" value="<?=$ck_sid ?>">
<input type="hidden" name="title" value="<?=strtr($LDCafeNews," ","+") ?>">
<input type="hidden" name="lang" value="<?=$lang ?>">
</form></body>
</html>
