<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
/**
* CARE 2002 Integrated Hospital Information System beta 1.0.03 - 2002-10-26
* GNU General Public License
* Copyright 2002 Elpidio Latorilla
* elpidio@latorilla.com
*
* See the file "copy_notice.txt" for the licence notice
*/
define('LANG_FILE','editor.php');
$local_user='ck_cafenews_user';
require_once('../include/inc_front_chain_lang.php');

$breakfile="cafenews.php?sid=".$sid."&lang=".$lang;

$dbtable="care_cafe_prices";

	/* Establish db connection */
require('../include/inc_db_makelink.php');
 	if ($link&&$DBLink_OK)
 	{
		if($mode=='save')
		{
			$savefail=0;
			for($i=0;$i<$maxitem;$i++)
			{
				$product="product$i";
				$item="item$i";
				$price="price$i";
				
				if($$item)
				{
					if(!$$product)
						$sql="DELETE FROM $dbtable WHERE item='".$$item."'";
					else
						$sql="UPDATE $dbtable SET productgroup='$groupname',article='".$$product."',price='".$$price."', modify_id='".$HTTP_COOKIE_VARS[$local_user.$sid]."'
							WHERE item='".$$item."'";
				}
				else
				{
					if($$product)
					$sql="INSERT INTO $dbtable (lang,productgroup,article,price,create_id,create_time)
							 VALUES ('$lang','$groupname','".$$product."','".$$price."','".$HTTP_COOKIE_VARS[$local_user.$sid]."',NULL)";
					else continue;
				}
				//echo $sql."<br>";
				if(!($ergebnis=mysql_query($sql,$link))) $savefail=1;
			}
			if($savefail) echo "<p>".$sql."<p>".$LDDbNoSave; 
				else {header("Location: cafenews-edit-price.php?sid=$sid&lang=$lang&mode=saveok&groupname=$groupname"); exit;}; 
		}
		else
		{
		 	$sql="SELECT * FROM $dbtable WHERE productgroup='$groupname'";
    
	         if(defined('LANG_DEPENDENT') && (LANG_DEPENDENT==1))
             {
	             $sql.="' AND lang='".$lang."'";
             }
			 
		 	$sql.=" ORDER BY article";

			if($ergebnis=mysql_query($sql,$link))
       		{
				$rows=0;
				while( $prod=mysql_fetch_array($ergebnis)) $rows++;
				if($rows)
				{
					mysql_data_seek($ergebnis,0);
				}
			}
				else echo "<p>".$sql."<p>$LDDbNoRead"; 
		}
    if(!$currency_short||!$currency_long)
	{
        $sql="SELECT short_name, long_name FROM care_currency WHERE status='main'";
		if($c_result=mysql_query($sql,$link))
		{
		   if(mysql_num_rows($c_result))
		   {
		      $currency=mysql_fetch_array($c_result);
			  $currency_short=$currency['short_name'];
			  $currency_long=$currency['long_name'];
		   } // else get default from ini file
		} // else get default from ini file
	}
  } else { echo "$LDDbNoLink<br> $sql<br>"; }
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 21.12.2001 -->
<head>
<?php echo setCharSet(); ?>
<title></title>

</head>
<body>
<FONT  SIZE=6 COLOR="#cc6600" FACE="verdana,Arial">
<a href="javascript:editcafe()"><img <?php echo createComIcon('../','basket.gif','0') ?>></a> <b><?php echo $LDCafePrices ?></b></FONT>

<form action="cafenews-edit-price.php" method="post"><hr>
<?php if($mode=="saveok") : ?>
<table border=0>
  <tr>
    <td><img <?php echo createMascot('../','mascot1_r.gif','0') ?>></td>
    <td colspan=2><FONT FACE="verdana,Arial"><FONT  SIZE=3 COLOR="#000066" FACE="verdana,Arial"><?php echo $LDPriceSaved ?></font><p>
			<font size=2><?php echo $LDClk2End ?> <input type="button" value="<?php echo $LDFinishBut ?>" onClick="window.location.replace('cafenews-prices.php?sid=<?php echo $sid."&lang=".$lang; ?>')">
                                                    </td>
  </tr>
</table>
<hr>
<?php endif ?>
<FONT  SIZE=2  FACE="verdana,Arial">
<?php echo $LDProdGroup ?>: <FONT  SIZE=3 COLOR="#000099" FACE="verdana,Arial"><?php echo $groupname; ?><font>
<p>
<table border=0 cellspacing=0>
  <tr bgcolor="ccffff" >
    <td><FONT  SIZE=2  FACE="verdana,Arial"><b><?php echo $LDProdName ?></b></td>
	 <td><FONT  SIZE=2  FACE="verdana,Arial">&nbsp;<b><?php echo $LDPrice." ".$currency_short." ".$currency_long ?></b></td>
  </tr>
<?php 
if($rows<10) $maxitem=10; else $maxitem=$rows+3;
for($i=0;$i<$maxitem;$i++)
{
$prod=mysql_fetch_array($ergebnis);
echo '
 <tr bgcolor="ccffff" >
    <td><input type="text" name="product'.$i.'" size=40 maxlength=40 value="'.$prod['article'].'">
        </td>
    <td><input type="text" name="price'.$i.'" size=4 maxlength=5 value="'.$prod['price'].'"> 
	<input type="hidden" name="item'.$i.'" value="'.$prod['item'].'">
 	</td>
  </tr>';
 }
?>
 <tr>    
 <td><p><br>
 <?php if($mode!="saveok") : ?>
	<a href="javascript:window.history.back()"><img <?php echo createLDImgSrc('../','back2.gif','0') ?>></a>
 <?php endif ?>
<input type="image" <?php echo createLDImgSrc('../','continue.gif','0') ?>>
  </td>  <td align=right><p><br><FONT FACE="verdana,Arial">
	<a href="<?php echo $breakfile ?>"><img <?php echo createLDImgSrc('../','cancel.gif','0') ?>></a>
	</td>
  </tr>
 </table>
<input type="hidden" name="sid" value="<?php echo $sid ?>">
<input type="hidden" name="lang" value="<?php echo $lang ?>">
<input type="hidden" name="maxitem" value="<?php echo $maxitem?>">
<input type="hidden" name="groupname" value="<?php echo $groupname?>">
<input type="hidden" name="currency_short" value="<?php echo $currency_short?>">
<input type="hidden" name="currency_long" value="<?php echo $currency_long?>">
<input type="hidden" name="mode" value="save">
</form></body>
</html>
