<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
/**
* CARE 2002 Integrated Hospital Information System beta 1.0.02 - 30.07.2002
* GNU General Public License
* Copyright 2002 Elpidio Latorilla
* elpidio@latorilla.com
*
* See the file "copy_notice.txt" for the licence notice
*/
define("LANG_FILE","editor.php");
$local_user="ck_cafenews_user";
require("../include/inc_front_chain_lang.php");
$breakfile="cafenews.php?sid=$sid&lang=$lang";

 $daytag=date("w");
 $day=date("d");
 $month=date("m");
 $year=date("Y");
 //print $daytag.$day.$month.$year."<p>";

 if(($daytag!=1)||($week!=1))
 {
	$JDday=GregorianToJD($month,$day,$year);
	if($daytag=="0") $JDday-=6;
	else $JDday=$JDday-($daytag-1);

	switch ($week)
	{
		case 2: $JDday+=7; break;
		case 3: $JDday+=14; break;
	}

	$datebuf=JDToGregorian($JDday);//print $datebuf;
	$arraybuf=explode("/",$datebuf);
	$month=$arraybuf[0];
	$day=$arraybuf[1];
	$year=$arraybuf[2];
	$daytag=date("w",mktime(0,0,0,$month,$day,$year));
 }
 
if(!$mday) 
{
	if($week==1)
	{
	$mday=date(d);
	$mmonth=date(m);
	$myear=date(Y);
	}
	else
	{
	$mday=$day;
	$mmonth=$month;
	$myear=$year;
	}
}


$dbtable="cafe_menu_".$lang;
require("../include/inc_db_makelink.php");
 if ($link&&$DBLink_OK)
 {
	 switch($mode)
	 {
	 	case "save":
				if($update)
				{
					$sql="UPDATE $dbtable SET menu='$menuplan' WHERE cyear='$myear' AND cmonth='$mmonth' AND cday='$mday'";	
				}
				else
				{
		 			$sql="INSERT INTO $dbtable 
						(	cyear,
							cmonth,
							cday,
							menu,
							encoder
							) VALUES 
						(	'$myear',
							'$mmonth',
							'$mday',
							'$menuplan',
							'$ck_cafenews_user'
							)";
				}					
				
				if($ergebnis=mysql_query($sql,$link))
       				{
						header("Location: cafenews-edit-menu.php?sid=$sid&lang=$lang&mode=saveok&week=$week&mday=$mday&mmonth=$mmonth&myear=$myear"); exit;
					}
					else print "<p>".$sql."<p>$LDDbNoSave"; 				
				break;
		default:
		 	$sql="SELECT menu FROM $dbtable WHERE cyear='$myear' AND cmonth='$mmonth' AND cday='$mday'";
			//print $sql;
			if($ergebnis=mysql_query($sql,$link))
       		{
							$rows=0;
							while( $content=mysql_fetch_array($ergebnis)) $rows++;
							if($rows)
							{
								mysql_data_seek($ergebnis,0);
								$content=mysql_fetch_array($ergebnis);
							}
			}
				else print "<p>".$sql."<p>".$LDDbNoRead; 
		} //end of switch
  } else print "$LDDbNoLink<br> $sql<br>";








function aligndate(&$ad,&$am,&$ay)
{
	if(!checkdate($am,$ad,$ay))
	{
		if($am==12)
		{
			$am=1;
			$ad=1;
			$ay++;
		}
		else
		{
			$am=$am+1;
    		$ad=1;
		}
	}
}
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 21.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>
<style type="text/css" name="s2">
.v18{ font-family:verdana,arial; color:#d6d6d6; font-size:18}
.v18_b{ font-family:verdana,arial; color:#000066; font-size:18}
</style>
</head>

<body onLoad="document.menuform.menuplan.focus()">

<FONT  SIZE=8 COLOR="#cc6600" FACE="verdana,Arial">
<img src="../img/basket.gif" width=74 height=70 border=0><b><?php echo $LDCafeMenu ?></b></FONT>
<form action="cafenews-edit-menu.php" method="post" name="menuform"><hr>
<table border=0 bgcolor="#000000" cellspacing=0 cellpadding=0>
  <tr>
    <td>

<table border=0 cellspacing=1 cellpadding=5>
  <tr>
    <td colspan=7 bgcolor="#ccffff">
	<FONT  SIZE=4 COLOR="#0000cc" FACE="verdana,Arial">
<?php switch($week)
	{
		case 1: print $LDThisWeek; break;
		case 2: print $LDNextWeek; break;
		case 3: print $LD3rdWeek; break;
	}
?>
</font>
</td>
  </tr>
  <tr bgcolor="#ccffff">
  
<?php for ($i=0,$acttag=$day,$dyidx=$daytag-1;$i<7;$i++,$acttag++,$dyidx++)
	{
	$spot=0;
	if ($mday==$acttag) 	$spot=1;
	aligndate($acttag,$month,$year);
	print ' 
    <td class="v18_b" ';
	if ($spot)  print ' bgcolor="yellow">';
		else print ' bgcolor="#ccffff">';
	print '<a href="';
	if($spot) print "#\""; else print 'cafenews-edit-menu.php?sid='.$sid.'&lang='.$lang.'&week='.$week.'&myear='.$year.'&mmonth='.$month.'&mday='.$acttag.'" ';
	print ' title="'.$acttag.'.'.$month.'.'.$year.'">';
	if($spot) print '<font color="#0000cc">';else print '<font color="#d6d6d6">';
	print '<b>'.$dayname[$dyidx].'</b>';
	if ($spot) print '</a>';
	print '</td>
	';
	}
?>

  </tr>
</table>
</td>
  </tr>
</table>



<p>
<table border=0 cellspacing=0>
  <tr bgcolor="#ccffff" >
    <td colspan=3><FONT  SIZE=2  FACE="verdana,Arial"><b><?php echo $LDMenu ?>:</b><br><font size=1><?php echo $LDPlsEnter ?>.<br>
	<textarea name="menuplan" cols=35 rows=10 wrap="physical"><?php echo $content[menu] ?></textarea>
 </td>
  </tr>

 <tr>
    <td ><p><br><FONT FACE="verdana,Arial">
	<a href="javascript:window.history.back()"><img src="../img/<?php echo $lang ?>/<?php echo $lang ?>_back2.gif" border=0></a>
	<a href="<?php echo $breakfile ?>"><img src="../img/<?php echo $lang ?>/<?php echo $lang ?>_cancel.gif" border=0></a>
  </td>
    <td align=right ><p><br><FONT FACE="verdana,Arial">
<input type="image" src="../img/<?php echo $lang ?>/<?php echo $lang ?>_continue.gif" border=0>
  </td>
     
<!--  <td>
		<input type="button" value="<?php echo $LDBackBut ?>" onClick="window.location.replace('cafenews-edit-menu-select-week.php?sid=<?php echo "$sid&lang=$lang" ?>')">&nbsp;&nbsp;&nbsp;
        <input type="button" value="<?php if($mode=="saveok") print $LDFinishBut; else print $LDCancelBut; ?>" onClick="window.location.replace('cafenews.php?sid=<?php echo "$sid&lang=$lang" ?>')">
		</td>

	<td align=right colspan=2><br><p><input type="submit" value="<?php echo $LDSaveBut ?>...">
	</td>
 -->  </tr>
 </table>
<input type="hidden" name="sid" value="<?php echo $sid ?>">
<input type="hidden" name="week" value="<?php echo $week ?>">
<input type="hidden" name="mode" value="save">
<input type="hidden" name="myear" value="<?php echo $myear ?>">
<input type="hidden" name="mmonth" value="<?php echo $mmonth ?>">
<input type="hidden" name="mday" value="<?php echo $mday ?>">
<input type="hidden" name="update" value="<?php echo $rows ?>">
<input type="hidden" name="lang" value="<?php echo $lang ?>">
</form></body>
</html>
