<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
/**
* CARE 2002 Integrated Hospital Information System beta 1.0.02 - 30.07.2002
* GNU General Public License
* Copyright 2002 Elpidio Latorilla
* elpidio@latorilla.com
*
* See the file "copy_notice.txt" for the licence notice
*/
define("LANG_FILE","editor.php");
$local_user="ck_cafenews_user";
require("../include/inc_front_chain_lang.php");

$breakfile="cafenews.php?sid=$sid&lang=$lang";

$dbtable="cafe_prices_".$lang;

	require("../include/inc_db_makelink.php");
 	if ($link&&$DBLink_OK)
 	{
		if($mode=="save")
		{
			$savefail=0;
			for($i=0;$i<$maxitem;$i++)
			{
				$product="product$i";
				$uid="uid$i";
				$pricedm="price_dm$i";
				$priceeuro="price_euro$i";
				
				if($$uid)
				{
					if(!$$product)
						$sql="DELETE FROM $dbtable WHERE uid='".$$uid."'";
					else
						$sql="UPDATE $dbtable SET productgroup='$groupname',article='".$$product."',price_dm='".$$pricedm."',price_euro='".$$priceeuro."'
							WHERE uid='".$$uid."'";
				}
				else
				{
					if($$product)
					$sql="INSERT INTO $dbtable (productgroup,article,price_dm,price_euro,uid)
							 VALUES ('$groupname','".$$product."','".$$pricedm."','".$$priceeuro."','".uniqid(rand(),true)."')";
					else continue;
				}
				//print $sql."<br>";
				if(!($ergebnis=mysql_query($sql,$link))) $savefail=1;
			}
			if($savefail) print "<p>".$sql."<p>Das speichern  aus der Datenbank $dbtable ist gescheitert."; 
				else {header("Location: cafenews-edit-price.php?sid=$sid&lang=$lang&mode=saveok&groupname=$groupname"); exit;}; 
		}
		else
		{
		 	$sql="SELECT * FROM $dbtable WHERE productgroup='$groupname' ORDER BY article";

			if($ergebnis=mysql_query($sql,$link))
       		{
				$rows=0;
				while( $prod=mysql_fetch_array($ergebnis)) $rows++;
				if($rows)
				{
					mysql_data_seek($ergebnis,0);
				}
			}
				else print "<p>".$sql."<p>$LDDbNoRead"; 
		}


  } else { print "$LDDbNoLink<br> $sql<br>"; }
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 21.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>

</head>
<body>
<FONT  SIZE=6 COLOR="#cc6600" FACE="verdana,Arial">
<a href="javascript:editcafe()"><img src="../img/basket.gif" width=74 height=70 border=0></a> <b><?php echo $LDCafePrices ?></b></FONT>

<form action="cafenews-edit-price.php" method="post"><hr>
<?php if($mode=="saveok") : ?>
<table border=0>
  <tr>
    <td><img src="../img/catr.gif" width=88 height=80 border=0></td>
    <td colspan=2><FONT FACE="verdana,Arial"><FONT  SIZE=3 COLOR="#000066" FACE="verdana,Arial"><?php echo $LDPriceSaved ?></font><p>
			<font size=2><?php echo $LDClk2End ?> <input type="button" value="<?php echo $LDFinishBut ?>" onClick="window.location.replace('cafenews-prices.php?sid=<?php echo $sid."&lang=".$lang; ?>')">
                                                    </td>
  </tr>
</table>
<hr>
<?php endif ?>
<FONT  SIZE=2  FACE="verdana,Arial">
<?php echo $LDProdGroup ?>: <FONT  SIZE=3 COLOR="#000099" FACE="verdana,Arial"><?php print $groupname; ?><font>
<p>
<table border=0 cellspacing=0>
  <tr bgcolor="ccffff" >
    <td><FONT  SIZE=2  FACE="verdana,Arial"><b><?php echo $LDProdName ?></b></td>
    <td><FONT  SIZE=2  FACE="verdana,Arial"><b><?php echo $LDPriceDM ?></b></td>
	 <td><FONT  SIZE=2  FACE="verdana,Arial">&nbsp;<b><?php echo $LDPriceEuro ?></b></td>
  </tr>
<?php 
if($rows<10) $maxitem=10; else $maxitem=$rows+3;
for($i=0;$i<$maxitem;$i++)
{
$prod=mysql_fetch_array($ergebnis);
print '
 <tr bgcolor="ccffff" >
    <td><input type="text" name="product'.$i.'" size=40 maxlength=40 value="'.$prod[article].'">
        </td>
    <td align=right><input type="text" name="price_dm'.$i.'" size=4 maxlength=5 value="'.$prod[price_dm].'">
	</td>
    <td><input type="text" name="price_euro'.$i.'" size=4 maxlength=5 value="'.$prod[price_euro].'"> 
	<input type="hidden" name="uid'.$i.'" value="'.$prod[uid].'">
 	</td>
  </tr>';
 }
?>
 <tr>    
 <td><p><br>
 <?php if($mode!="saveok") : ?>
<!--  	<input type="button" value="<?php echo $LDBackBut ?>" onClick="window.history.back()">
 -->	<a href="javascript:window.history.back()"><img src="../img/<?php echo $lang ?>/<?php echo $lang ?>_back2.gif" border=0></a>
 <?php endif ?>
	<a href="<?php echo $breakfile ?>"><img src="../img/<?php echo $lang ?>/<?php echo $lang ?>_cancel.gif" border=0></a>
<!--         <input type="button" value="<?php echo $LDCancelBut ?>" onClick="window.location.replace('cafenews.php?sid=<?php echo "$sid&lang=$lang" ?>')">
 -->  </td>  <td align=right><p><br><FONT FACE="verdana,Arial">
<!-- 		<input type="submit" value="<?php echo $LDSaveBut ?>">
 --><input type="image" src="../img/<?php echo $lang ?>/<?php echo $lang ?>_continue.gif" border=0>
	</td>
  </tr>
 </table>
<input type="hidden" name="sid" value="<?php echo $sid ?>">
<input type="hidden" name="lang" value="<?php echo $lang ?>">
<input type="hidden" name="maxitem" value="<?php echo $maxitem?>">
<input type="hidden" name="groupname" value="<?php echo $groupname?>">
<input type="hidden" name="mode" value="save">
</form></body>
</html>
