<?
if(!$lang)
	if(!$ck_language) include("../chklang.php");
		else $lang=$ck_language;
if(!$sid||($sid!=$ck_sid)||!$ck_editor_user) { header("location:../language/$lang/lang_".$lang."_invalid-access-warning.php"); exit;}

//print $lang;

require("../language/".$lang."/lang_".$lang."_editor.php");

switch($target)
{
	case "headline":$breakfile="startframe.php?srcpath=reader&lang=$lang";
							//$title="Schalgzeilen";
							break;

	case "cafenews":$breakfile="cafenews.php?srcpath=reader&lang=$lang";
							//$title="Schalgzeilen";
							break;
	/*	
	case "healthtips":$breakfile="gesundtips.php?srcpath=reader";
							$title="Gesundheitstips";
							break;
	case "adv_studies":$breakfile="gesundtips.php?srcpath=reader";
							$title="Fortbildung";
							break;
	case "prof_training":$breakfile="gesundtips.php?srcpath=reader";
							$title="Ausbildung";
							break;
	case "physiotherapy":$breakfile="gesundtips.php?srcpath=reader";
							$title="Physioherapie";
							break;
	case "events":$breakfile="gesundtips.php?srcpath=reader";
							$title="Veranstaltungen";
							break;
	*/
	//default: header("location:invalid-access-warning.php"); exit;
	default:	$breakfile="newscolumns.php?sid=$ck_sid&target=$target&lang=$lang&title=$title";

}

?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 21.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>

<script language="javascript">
function chkForm(d)
{
	if((d.artopt[0].checked)||(d.artopt[1].checked)||(d.artopt[2].checked)||(d.artopt[3].checked)||(d.artopt[4].checked)) return true;
		else return false;
}
</script>

</head>
<body>
<form name="selectform" method="get" action="editor-4plus1.php" onSubmit="return chkForm(this)">
<FONT  SIZE=6 COLOR="#cc6600" FACE="verdana,Arial">
<b><?=$title ?></b></FONT>
<hr>
<table border=0>
  <tr>
    <td><img src="../img/catr.gif" width=88 height=80 border=0></td>
    <td colspan=2><FONT FACE="verdana,Arial"><FONT  SIZE=5 COLOR="#000066" FACE="verdana,Arial"><?=$LDWhereTo ?></font><br>
			<font size=2><?=$LDPlsSelect ?></td>
  </tr>
  <tr>
    <td bgcolor="ccffff" colspan=3><FONT FACE="verdana,Arial"><p>
		<img src="../img/healthtips.jpg" width=402 height=428 border=0 align=right>		
		<input type="radio" name="artopt" value="1"> <a href="#" onClick="document.selectform.artopt[0].checked=true"><?=$LDArticle1 ?></a><br>
    	<input type="radio" name="artopt" value="2"> <a href="#" onClick="document.selectform.artopt[1].checked=true"><?=$LDArticle2 ?></a><br>
    	<input type="radio" name="artopt" value="3"> <a href="#" onClick="document.selectform.artopt[2].checked=true"><?=$LDArticle3 ?></a><br>
    	<input type="radio" name="artopt" value="4"> <a href="#" onClick="document.selectform.artopt[3].checked=true"><?=$LDArticle4 ?></a><br>
     	<input type="radio" name="artopt" value="5"> <a href="#" onClick="document.selectform.artopt[4].checked=true"><?=$LDArticle5 ?></a><br><p>
</td>
  </tr>
  <tr>
    <td colspan=2><FONT FACE="verdana,Arial">
		<input type="button" value="<?=$LDBackBut ?>" onClick="window.history.back()">&nbsp;&nbsp;
		<input type="button" value="<?=$LDCancelBut ?>"  onClick="window.location.replace('<?=$breakfile ?>')">
  </td>
    <td align=right ><FONT FACE="verdana,Arial">
		<input type="submit" value="<?=$LDContinueBut ?>">
  </td>
  </tr>
</table>
<input type="hidden" name="sid" value="<?=$ck_sid ?>">
<input type="hidden" name="target" value="<?=$target ?>">
<input type="hidden" name="title" value="<?=$title ?>">

</form>
</body>
</html>
