<?php
error_reporting(E_COMPILE_ERROR|E_ERROR|E_CORE_ERROR);
require('./roots.php');
require($root_path.'include/inc_environment_global.php');
/**
* CARE 2002 Integrated Hospital Information System beta 1.0.04 - 2003-03-31
* GNU General Public License
* Copyright 2002 Elpidio Latorilla
* elpidio@latorilla.com
*
* See the file "copy_notice.txt" for the licence notice
*/
define('LANG_FILE','nursing.php');
define('NO_2LEVEL_CHK',1);
require_once($root_path.'include/inc_front_chain_lang.php');
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14.10.01 -->
<head>
<?php echo setCharSet(); ?>

</head>
<body><font size=5 face=arial color=maroon><?php echo $LDPreview ?><p>


<img src="../../gui/img/common/default/pixel.gif" border=0  name="preview">
<form name="picnotes">
<table border=0 cellspacing=0 cellpadding=0>
  <tr>
    <td><font size=2 face=arial color=maroon><?php echo $LDShotDate ?>:
</td>
    <td><input type="text" name="sdate" size=15 maxlength=15><div id="shotdate"></div></td>
  </tr>
  <tr>
    <td><font size=2 face=arial color=maroon><?php echo $LDShotNr ?>:</td>
    <td><input type="text" name="nr" size=2 maxlength=3><div id="snr"></div></td>
  </tr>
</table>
<textarea name="notes" cols=40 rows=4 wrap="physical">
</textarea><div id="notes"></div>
</form>
</body>
</html>
