<?php
require_once($root_path.'include/inc_config_color.php');
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 12.01.2002 -->
<head>
<?php echo setCharSet(); ?>
<title></title>
<meta name="Description" content="">
<meta name="Keywords" content="">
<meta name="Author" content="Lorilla Bong">
<meta name="Generator" content="AceHTML 4 Freeware">
</head>
<body bgcolor="<?php echo $cfg['idx_bgcolor'] ?>">


</body>
</html>
