<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 26.05.01 -->
<head>
<?php echo setCharSet(); ?>
<title></title>
<meta name="Description" content="">
<meta name="Keywords" content="">
<meta name="Author" content="Lorilla Bong">
<meta name="Generator" content="AceHTML 4 Freeware">
</head>
<body>
<a href="<?php
echo "pflege-station.php?mode=getlast&rt=pflege&sid=$sid&station=".$station."&pyear=".$pyear."&pmonth=".$pmonth."&pday=".$pday."&c=".$c;
?>">Bitte clicken Sie hier an.....
</a>
</body>
</html>
