<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 26.05.01 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>
<meta name="Description" content="">
<meta name="Keywords" content="">
<meta name="Author" content="Lorilla Bong">
<meta name="Generator" content="AceHTML 4 Freeware">
</head>
<body>
<a href="<?php
print "pflege-station.php?mode=getlast&rt=pflege&sid=".$ck_sid."&station=".$station."&pyear=".$pyear."&pmonth=".$pmonth."&pday=".$pday."&c=".$c;
?>">Bitte clicken Sie hier an.....
</a>
</body>
</html>
