<?php
if(!$lang)
	if(!$ck_language) include("../chklang.php");
		else $lang=$ck_language;
if (!$sid||($sid!=$ck_sid)) {header("Location:../language/".$lang."/lang_".$lang."_invalid-access-warning.php"); exit;}; 
require("../language/".$lang."/lang_".$lang."_products.php");
//require("../req/config-color.php");

//set order catalog flag
$bcat=true;

require("../req/products-search-mod.php");
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 24.07.01 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title><?=$title_art?></title>
<meta name="Description" content="">
<meta name="Keywords" content="">
<meta name="Author" content="Lorilla Bong">
<meta name="Generator" content="AceHTML 4 Freeware">
</head>
<body bgcolor="#ffffff" onLoad="if (window.focus) window.focus()">
<?
require("../req/products-search-result-mod.php");
?>
<p>
<a href="<? if($goback) print "javascript:window.history.back()"; else print "javascript:window.close()"; ?>"><img src="../img/<?="$lang/$lang" ?>_close2.gif" width=103 height=24 border=0></a>

</body>
</html>
