<?php
require_once('../../include/inc_vars_resolve.php');
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<head>
<title>Créditos</title>
</head>
<body onLoad="if(window.focus) window.focus()">
<font face="verdana,arial" size=6 color="#0000ff">Créditos</fonts>
<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
            <P><img src="../../gui/img/common/default/pixel.gif"  border=0  align=right vspace=10 width=135>
			<b>Alfredo Rodrigues (PT) traduziu o Care 2002  para Português.</b>
			
			<P><a href="mailto:ajcrodm@yahoo.com"><u>Alfredo Rodrigues pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>
<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../fotos/credits/elpidio_latorilla_3.jpg" border=0  align=right vspace=10>
			<b>A primeira versão beta do CARE 2002 foi criada por Elpidio Latorilla:</b>
			<p>
			Profissões: <br>Programador, Enfermeiro de Cirúrgia, Técnico de Electrónica e Telecomunicações
			<p>
			Áreas de interesse: <br>C, C++, PHP, Javascript, SQL, TCL/TK, HTML, Perl, ASP, Java
			<P><a href="mailto:elpidio@latorilla.com"><u>Elpidio Latorilla pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>
<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../fotos/credits/giuseppe_scarpi.jpg"  border=0  width=135 height=170 align=right vspace=10>
			<b>Giuseppe Scarpi (IT) traduziu o Care 2002 para Italiano.</b>
			<p>
			Giuseppe Scarpi nasceu em Roma, Italia e tem 35 anos. 
			<p>É graduado em Engenharia Electrónica e tem trabalhado em várias empresas no sector biomédico, 
			onde desenvolveu os seus conhecimentos sobre as relações entre o mundo médico e o mundo da informática.<br>
Utiliza e aprecia tanto o Linux como o Windows, "<i>Ambos são o resultado de um grande trabalho humano e devem ser respeitados</i>".<p>
Decidiu aderir activamente ao Código Aberto porque: <br><i>"Um mundo ideal só pode sobreviver se perfeitamente balanceado. Se se retira algo,
 deve-se também retribuir na mesma proporção."</i>

			<P><a href="mailto:kalbun@inwind.it"><u>Giuseppe Scarpi pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>

<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
            <P><img src="../../fotos/credits/gabriele_cicala.jpg"  border=0  align=right vspace=10>
			<b>Gabriele Cicala (IT) traduziu grande parte do site www.care2x.com para Italiano.</b>
			
			<P><a href="mailto:gabcicala@tiscali.it"><u>Gabriele Cicala pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>

<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
            <P><img src="../../fotos/credits/daniel_zilli.jpg"  border=0  align=right vspace=10>
			<b>Daniel Zilli (BR) traduziu o Care 2002 e o site www.care2x.com para Português-Brasileiro.</b>
			<p>
			Daniel é um bom rapaz que quer viver uma vida feliz. Gosta de computadores, futebol e boa música.
Tem 10 anos de experência em computadores e adora o que faz.
O Daniel tem uma empresa onde trabalha com produtos para ensino de informática, software de código aberto e tem a sua própria distribuição de linux.
			<P><a href="mailto:danielz@cco.matrix.com.br"><u>Daniel Zilli pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>

<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
            <P><img src="../../fotos/credits/agus_mr.jpg"  border=0  align=right vspace=10>
			<b>Agus Muhammad Ramdan (ID) traduziu o Care 2002 e o site www.care2x.com para Indonésio.</b>
			
			<P><a href="mailto:agusmr@mweb.co.id"><u>Agus M. Ramdan pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>
<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../gui/img/control/default/<?php echo $lang ?>/<?php echo $lang ?>_x-blank.gif"  border=0  width=135 align=right vspace=10>
			<b>Thomas Wiedmann (DE) contribuiu com:</b>
			<p><font size=1>
			Testes completos<br>
			Depuração<br>
			Conceito da BD 'optimistic locking'<br>
			Optimizações da BD<br>
			Scripts de validação para datas e números<p>
			</font>
			Thomas Wiedmann desenvolve software há bastante tempo e trabalha em Estugarda, Alemanha. Ele tem
			trabalhado com a Gupta Team Developer, com IBM DB2 nos últimos 7 anos e é também
			IBM Certified UDB DB2 Administrator. Leia mais sobre DB2 no seu livro
			"DB2" ISBN 3-932311-80-9. É o autor de TOOLBOX (www.toolbox-mag.de),
			uma revista alemã sobre programação.
		

			<P><a href="mailto:tho123@users.sourceforge.net"><u>Thomas Wiedmann pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>

<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../gui/img/control/default/<?php echo $lang ?>/<?php echo $lang ?>_x-blank.gif"  border=0  width=135 align=right vspace=10>
			<b>Nino Novak (DE) editou o site www.care2x.com em Alemão.</b>
			<p>
			Nino Novak é um pobre e solitário cowboy. Dispara mais depressa do que pensa. As vezes é um pouco inquieto.
			Adora "real gurus" e ter discussões sofisticadas com eles. Quer ajudar a criar um mundo melhor.
			Tem alguns conhecimentos científicos e médicos (pelo que se juntou ao projecto care2x).
		

			<P><a href="mailto:nino@kflog.org"><u>Nino Novak pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>
<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../gui/img/control/default/<?php echo $lang ?>/<?php echo $lang ?>_x-blank.gif"  border=0  width=135 align=right vspace=10>
			<b>Patxi Gomaríz (ES) traduziu o Care 2002 para Espanhol.</b>
			<p>
			Patxi Gomaríz nasceu na primavera de 1966 em Murcia, Espanha. A sua vida e o seu trabalho centram-se principalmente na fotografia,
			é um especialista em fotografia para Oftalmologia (fundus camera). É um entusiasta da Internet e também desenvolve sites.<p>
			"<i>Eu penso que o Código Aberto é uma arma efectiva contra os efeitos negativos da economia globalizada especialmente em 
			áreas tão fundamentais para a humanidade como a saúde. Por esta razão, sinto muito orgulho na minha pequena contribuição
			para este grande projecto.</i>"

			<P><a href="mailto:pgomariz@ono.com"><u>Patxi Gomaríz pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>
<hr>
<TABLE cellSpacing=0 cellPadding=0 border=0 width=100%>
        <TBODY>
        <TR>
          <TD><IMG height=15 
            src="../../gui/img/common/default/pixel.gif" 
            width=5 border=0></TD></TR>
        <TR>
          <TD vAlign=top><font face="verdana,arial" size=2>
			<P><img src="../../gui/img/control/default/<?php echo $lang ?>/<?php echo $lang ?>_x-blank.gif"  border=0  width=135 align=right vspace=10>
			<b>Daniele Frijia (DE) verificou o Care 2002 no que diz respeito a segurança.</b>
			<br>
			Algumas das suas contribuições:<p>
			<font size=1>
			Conselhos sobre segurança<br>
			Consultoria sobre questões de PHP<br>
			Ele é o "sentinela" do projecto
		</font>
		    <p>
			Daniele Frijia (nascido em 81), trabalha actualmente para um ISP em Nuremberga, Alemanha, dedica os seus conhecimentos de PHP
			à melhoria, em termos de segurança, do Care2x. A intenção é abrir as portas de um novo "mercado" (médico)
			à comunidade do Código Aberto.

			<P><a href="mailto:daniele@infra.de"><u>Daniele Frijia pode ser contactado aqui.</u></a>
</TD></TR></TBODY></TABLE>
<hr>
<font face="verdana,arial" size=3 color="#0000ff">Mais Créditos</font>
<font face="verdana,arial" size=1 > (por ordem alfabética)</font>

<table border=0 cellspacing=1 cellpadding=1>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Agus M. Ramdan (ID)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Revisões ao código, care2x.com CMS</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Daniele Frijia (DE)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Testes de segurança, Consultoria PHP</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Dilip Bharatee (IN)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;ecomscience.com, programadores a tempo inteiro</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Luki Rustianto (ID)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Melhorias de segurança</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Matêj Hausenblas (FR)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Tradução para Francês</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Muhammad Panji (ID)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Traduções adicionais para Indonésio</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Nino Novak (DE)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Edição Alemã do www.care2x.com</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Patxi Gomaríz (ES)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Tradução para Espanhol</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Pawel Cyrta (PL)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Tradução para Polaco</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Prantar Deka (IN)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Módulo genérico de facturação</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Roberto Nanucci (IT)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;care2x.it espelho do site</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Simone Aveotti (IT)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Traduções adicionais para Italiano</font></td>
  </tr>
  <tr>
    <td bgcolor="#efefef"><nobr><img src="../../gui/img/common/default/redpfeil.gif" border=0 width=4 height=7 align="absmiddle"><font face="verdana,arial" size=2> Thomas Wiedmann (DE)</font></nobr>&nbsp;</td>
    <td bgcolor="#f9f9f9"><font face="verdana,arial" size=2>&nbsp;&nbsp;Testes, depuração e validações de scripts</font></td>
  </tr>
</table>

<font face="verdana,arial" size=1>Nota: Esta é uma lista parcial. Mais Créditos irão ser adicionados.</font>

</body>
</html>
