<?

$finalbuf=get_meta_tags("ai/filters/adj-metafilter.htm");

require("../req/db_dbp.php");

$link=mysql_connect($dbhost,$dbusername,$dbpassword);
 if ($link)
 {
	if(mysql_select_db($dbname,$link)) 
	{	

		
			$savefail=0;
	/* $dbtable="aia_query2action";
		while(list($x,$v)=each($finalbuf))
			{
				parse_str($v,$pstr);
					$q=explode("_",$x);
					$sql="INSERT INTO $dbtable (query_1,query_2,query_3,query_4,action,object,txtfile_path)
							 VALUES ('$q[0]','$q[1]','$q[2]','$q[3]','".$pstr[action]."','".$pstr[object]."','".$pstr[path]."')";

				print $sql."<br>";
				if(!($ergebnis=mysql_query($sql,$link))) $savefail=1;
			}
			if($savefail) print "<p>".$sql."<p>Das speichern  aus der Datenbank $dbtable ist gescheitert."; 
	*/
		 $dbtable="aia_adj_filter_de";
			while(list($x,$v)=each($finalbuf))
			{
				parse_str($v,$pstr);
					//$q=explode("_",$x);
					$sql="INSERT INTO $dbtable (mainform,subforms)
							 VALUES ('$x','$v')";

				print $sql."<br>";
				if(!($ergebnis=mysql_query($sql,$link))) $savefail=1;
			}
			if($savefail) print "<p>".$sql."<p>Das speichern  aus der Datenbank $dbtable ist gescheitert."; 
				
	}
} 

		

?><html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 25.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>
<meta name="Description" content="">
<meta name="Keywords" content="">
<meta name="Author" content="Lorilla Bong">
<meta name="Generator" content="AceHTML 4 Freeware">
</head>
<body>


</body>
</html>
