<?
if(!$lang)
	if(!$ck_language) include("../chklang.php");
		else $lang=$ck_language;
if (!$sid||($sid!=$ck_sid)) {header("Location:../language/".$lang."/lang_".$lang."_invalid-access-warning.php"); exit;}; 

require("../language/".$lang."/lang_".$lang."_editor.php");

$dbtable="cafe_prices_".$lang;

	require("../req/db-makelink.php");
 	if ($link&&$DBLink_OK)
 	{
		if($mode=="save")
		{
			$savefail=0;
			for($i=0;$i<$maxitem;$i++)
			{
				$product="product$i";
				$uid="uid$i";
				$pricedm="price_dm$i";
				$priceeuro="price_euro$i";
				
				if($$uid)
				{
					if(!$$product)
						$sql="DELETE FROM $dbtable WHERE uid='".$$uid."'";
					else
						$sql="UPDATE $dbtable SET productgroup='$groupname',article='".$$product."',price_dm='".$$pricedm."',price_euro='".$$priceeuro."'
							WHERE uid='".$$uid."'";
				}
				else
				{
					if($$product)
					$sql="INSERT INTO $dbtable (productgroup,article,price_dm,price_euro,uid)
							 VALUES ('$groupname','".$$product."','".$$pricedm."','".$$priceeuro."','".uniqid(rand(),true)."')";
					else continue;
				}
				//print $sql."<br>";
				if(!($ergebnis=mysql_query($sql,$link))) $savefail=1;
			}
			if($savefail) print "<p>".$sql."<p>Das speichern  aus der Datenbank $dbtable ist gescheitert."; 
				else {header("Location: cafenews-edit-price.php?sid=$ck_sid&mode=saveok&groupname=$groupname"); exit;}; 
		}
		else
		{
		 	$sql="SELECT * FROM $dbtable WHERE productgroup='$groupname' ORDER BY article";

			if($ergebnis=mysql_query($sql,$link))
       		{
				$rows=0;
				while( $prod=mysql_fetch_array($ergebnis)) $rows++;
				if($rows)
				{
					mysql_data_seek($ergebnis,0);
				}
			}
				else print "<p>".$sql."<p>$LDDbNoRead"; 
		}


  } else { print "$LDDbNoLink<br> $sql<br>"; }


?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 21.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>

</head>
<body>
<FONT  SIZE=6 COLOR="#cc6600" FACE="verdana,Arial">
<a href="javascript:editcafe()"><img src="../img/basket.gif" width=74 height=70 border=0></a> <b><?=$LDCafePrices ?></b></FONT>
<form action="cafenews-edit-price.php" method="post"><hr>
<? if($mode=="saveok") : ?>
<table border=0>
  <tr>
    <td><img src="../img/catr.gif" width=88 height=80 border=0></td>
    <td colspan=2><FONT FACE="verdana,Arial"><FONT  SIZE=3 COLOR="#000066" FACE="verdana,Arial"><?=$LDPriceSaved ?></font><p>
			<font size=2><?=$LDClk2End ?> <input type="button" value="<?=$LDFinishBut ?>" onClick="window.location.replace('cafenews-prices.php?sid=<?=$ck_sid ?>')">
                                                    </td>
  </tr>
</table>
<hr>
<? endif ?>
<FONT  SIZE=2  FACE="verdana,Arial">
<?=$LDProdGroup ?>: <FONT  SIZE=3 COLOR="#000099" FACE="verdana,Arial"><? print $groupname; ?><font>
<p>
<table border=0 cellspacing=0>
  <tr bgcolor="ccffff" >
    <td><FONT  SIZE=2  FACE="verdana,Arial"><b><?=$LDProdName ?></b></td>
    <td><FONT  SIZE=2  FACE="verdana,Arial"><b><?=$LDPriceDM ?></b></td>
	 <td><FONT  SIZE=2  FACE="verdana,Arial">&nbsp;<b><?=$LDPriceEuro ?></b></td>
  </tr>
<? 
if($rows<10) $maxitem=10; else $maxitem=$rows+3;
for($i=0;$i<$maxitem;$i++)
{
$prod=mysql_fetch_array($ergebnis);
print '
 <tr bgcolor="ccffff" >
    <td><input type="text" name="product'.$i.'" size=40 maxlength=40 value="'.$prod[article].'">
        </td>
    <td align=right><input type="text" name="price_dm'.$i.'" size=4 maxlength=5 value="'.$prod[price_dm].'">
	</td>
    <td><input type="text" name="price_euro'.$i.'" size=4 maxlength=5 value="'.$prod[price_euro].'"> 
	<input type="hidden" name="uid'.$i.'" value="'.$prod[uid].'">
 	</td>
  </tr>';
 }
?>
 <tr>    
 <td><p><br>
 <? if($mode!="saveok") : ?>
 	<input type="button" value="<?=$LDBackBut ?>" onClick="window.history.back()">
 <? endif ?>
        <input type="button" value="<?=$LDCancelBut ?>" onClick="window.location.replace('cafenews.php?sid=<?="$ck_sid&lang=$lang" ?>')"></td>
    <td align=right><p><br><FONT FACE="verdana,Arial">
		<input type="submit" value="<?=$LDSaveBut ?>">
	</td>
  </tr>
 </table>
<input type="hidden" name="sid" value="<?=$ck_sid ?>">
<input type="hidden" name="maxitem" value="<?=$maxitem?>">
<input type="hidden" name="groupname" value="<?=$groupname?>">
<input type="hidden" name="mode" value="save">
</form></body>
</html>
