<?
if(!$lang)
	if(!$ck_language) include("../chklang.php");
		else $lang=$ck_language;
if (!$sid||($sid!=$ck_sid)) {header("Location:../language/".$lang."/lang_".$lang."_invalid-access-warning.php"); exit;}; 
require("../language/".$lang."/lang_".$lang."_editor.php");

 $daytag=date("w");
 $day=date("d");
 $month=date("m");
 $year=date("Y");
 //print $daytag.$day.$month.$year."<p>";

 if(($daytag!=1)||($week!=1))
 {
	$JDday=GregorianToJD($month,$day,$year);
	if($daytag=="0") $JDday-=6;
	else $JDday=$JDday-($daytag-1);

	switch ($week)
	{
		case 2: $JDday+=7; break;
		case 3: $JDday+=14; break;
	}

	$datebuf=JDToGregorian($JDday);//print $datebuf;
	$arraybuf=explode("/",$datebuf);
	$month=$arraybuf[0];
	$day=$arraybuf[1];
	$year=$arraybuf[2];
	$daytag=date("w",mktime(0,0,0,$month,$day,$year));
 }
 
if(!$mday) 
{
	if($week==1)
	{
	$mday=date(d);
	$mmonth=date(m);
	$myear=date(Y);
	}
	else
	{
	$mday=$day;
	$mmonth=$month;
	$myear=$year;
	}
}


$dbtable="cafe_menu_".$lang;
require("../req/db-makelink.php");
 if ($link&&$DBLink_OK)
 {
	 switch($mode)
	 {
	 	case "save":
				if($update)
				{
					$sql="UPDATE $dbtable SET menu='$menuplan' WHERE cyear='$myear' AND cmonth='$mmonth' AND cday='$mday'";	
				}
				else
				{
		 			$sql="INSERT INTO $dbtable 
						(	cyear,
							cmonth,
							cday,
							menu,
							encoder
							) VALUES 
						(	'$myear',
							'$mmonth',
							'$mday',
							'$menuplan',
							'$ck_cafenews_user'
							)";
				}					
				
				if($ergebnis=mysql_query($sql,$link))
       				{
						header("Location: cafenews-edit-menu.php?sid=$ck_sid&lang=$lang&mode=saveok&week=$week&mday=$mday&mmonth=$mmonth&myear=$myear"); exit;
					}
					else print "<p>".$sql."<p>$LDDbNoSave"; 				
				break;
		default:
		 	$sql="SELECT menu FROM $dbtable WHERE cyear='$myear' AND cmonth='$mmonth' AND cday='$mday'";
			//print $sql;
			if($ergebnis=mysql_query($sql,$link))
       		{
							$rows=0;
							while( $content=mysql_fetch_array($ergebnis)) $rows++;
							if($rows)
							{
								mysql_data_seek($ergebnis,0);
								$content=mysql_fetch_array($ergebnis);
							}
			}
				else print "<p>".$sql."<p>".$LDDbNoRead; 
		} //end of switch
  } else print "$LDDbNoLink<br> $sql<br>";








function aligndate(&$ad,&$am,&$ay)
{
	if(!checkdate($am,$ad,$ay))
	{
		if($am==12)
		{
			$am=1;
			$ad=1;
			$ay++;
		}
		else
		{
			$am=$am+1;
    		$ad=1;
		}
	}
}
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 21.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>
<style type="text/css" name="s2">
.v18{ font-family:verdana,arial; color:#d6d6d6; font-size:18}
.v18_b{ font-family:verdana,arial; color:#000066; font-size:18}
</style>
</head>

<body onLoad="document.menuform.menuplan.focus()">

<FONT  SIZE=8 COLOR="#cc6600" FACE="verdana,Arial">
<img src="../img/basket.gif" width=74 height=70 border=0><b><?=$LDCafeMenu ?></b></FONT>
<form action="cafenews-edit-menu.php" method="post" name="menuform"><hr>
<table border=0 bgcolor="#000000" cellspacing=0 cellpadding=0>
  <tr>
    <td>

<table border=0 cellspacing=1 cellpadding=5>
  <tr>
    <td colspan=7 bgcolor="#ccffff">
	<FONT  SIZE=4 COLOR="#0000cc" FACE="verdana,Arial">
<? switch($week)
	{
		case 1: print $LDThisWeek; break;
		case 2: print $LDNextWeek; break;
		case 3: print $LD3rdWeek; break;
	}
?>
</font>
</td>
  </tr>
  <tr bgcolor="#ccffff">
  
<? for ($i=0,$acttag=$day,$dyidx=$daytag-1;$i<7;$i++,$acttag++,$dyidx++)
	{
	$spot=0;
	if ($mday==$acttag) 	$spot=1;
	aligndate($acttag,$month,$year);
	print ' 
    <td class="v18_b" ';
	if ($spot)  print ' bgcolor="yellow">';
		else print ' bgcolor="#ccffff">';
	print '<a href="';
	if($spot) print "#\""; else print 'cafenews-edit-menu.php?sid='.$ck_sid.'&week='.$week.'&myear='.$year.'&mmonth='.$month.'&mday='.$acttag.'" ';
	print ' title="'.$acttag.'.'.$month.'.'.$year.'">';
	if($spot) print '<font color="#0000cc">';else print '<font color="#d6d6d6">';
	print '<b>'.$dayname[$dyidx].'</b>';
	if ($spot) print '</a>';
	print '</td>
	';
	}
?>

  </tr>
</table>
</td>
  </tr>
</table>



<p>
<table border=0 cellspacing=0>
  <tr bgcolor="#ccffff" >
    <td colspan=3><FONT  SIZE=2  FACE="verdana,Arial"><b><?=$LDMenu ?>:</b><br><font size=1><?=$LDPlsEnter ?>.<br>
	<textarea name="menuplan" cols=35 rows=10 wrap="physical"><?=$content[menu] ?></textarea>
 </td>
  </tr>

 <tr>    
 <td><p><br>
		<input type="button" value="<?=$LDBackBut ?>" onClick="window.location.replace('cafenews-edit-menu-select-week.php?sid=<?=$ck_sid ?>')">&nbsp;&nbsp;&nbsp;
        <input type="button" value="<? if($mode=="saveok") print $LDFinishBut; else print $LDCancelBut; ?>" onClick="window.location.replace('cafenews.php?sid=<?=$ck_sid ?>')">
		</td>

	<td align=right colspan=2><br><p><input type="submit" value="<?=$LDSaveBut ?>...">
	</td>
  </tr>
 </table>
<input type="hidden" name="sid" value="<?=$ck_sid ?>">
<input type="hidden" name="week" value="<?=$week ?>">
<input type="hidden" name="mode" value="save">
<input type="hidden" name="myear" value="<?=$myear ?>">
<input type="hidden" name="mmonth" value="<?=$mmonth ?>">
<input type="hidden" name="mday" value="<?=$mday ?>">
<input type="hidden" name="update" value="<?=$rows ?>">
<input type="hidden" name="lang" value="<?=$lang ?>">
</form></body>
</html>
