<?
if(!$lang)
	if(!$ck_language) include("../chklang.php");
		else $lang=$ck_language;
if (!$sid||($sid!=$ck_sid)) {header("Location:../language/".$lang."/lang_".$lang."_invalid-access-warning.php"); exit;}; 

require("../language/".$lang."/lang_".$lang."_editor.php");

if($groupopt)
switch($groupopt)
{
	case "newgroup":	header("Location: cafenews-edit-price-newgroup.php?sid=$ck_sid&lang=$lang");
						break;
	default: header("Location: cafenews-edit-price.php?sid=$ck_sid&groupname=$groupopt&lang=$lang");break; 
}


$dbtable="cafe_prices_".$lang;

require("../req/db-makelink.php");
 if ($link&&$DBLink_OK)
 {
		 	$sql="SELECT article FROM $dbtable 
							WHERE description='group'";	
			if($ergebnis=mysql_query($sql,$link))
       		{
				$rows=0;
				while( $ginfo=mysql_fetch_array($ergebnis)) $rows++;
				if($rows)
				{
					mysql_data_seek($ergebnis,0);
				}
			}
				else print "<p>".$sql."<p>$LDDbNoRead"; 

  } else { print "$LDDbNoLink<br> $sql<br>"; }


?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 21.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>

<? if($rows) : ?>
<script language="javascript">
function chkForm(d)
{
	var opt=<?=$rows+1 ?>;
	if(opt==2)
	{
		if((d.groupopt[0].checked)||(d.groupopt[1].checked)) return true;
		else return false;
	}
	else
	{
		for(i=0;i<opt;i++)
		{
			if(d.groupopt[i].checked) return true;
		}
		return false;
	}
}
</script>
<? endif ?>

</head>
<body>
<FONT  SIZE=8 COLOR="#cc6600" FACE="verdana,Arial">
<a href="javascript:editcafe()"><img src="../img/basket.gif" width=74 height=70 border=0></a> <b><?=$LDCafePrices ?></b></FONT>
<hr>
<form name="selectform" action="cafenews-edit-price-select.php" <? if($rows) print 'onSubmit="return chkForm(this)"'; ?>>
<table border=0>
  <tr>
    <td><img src="../img/catr.gif" width=88 height=80 border=0></td>
    <td colspan=2><FONT  SIZE=4 COLOR="#000066" FACE="verdana,Arial">
<? if ($rows) : ?>
			<?=$LDMarkGroup ?>
<? else : ?>
			<?=$LDCreateGroupPrompt ?>
<? endif ?>
	</td>
  </tr>
<? if($rows)
{
	print '
  <tr>
    <td>&nbsp;</td>
    <td bgcolor="ccffff" colspan=2><FONT FACE="verdana,Arial"><p><br>';
	for($i=0;$i<$rows;$i++)
	{
		$ginfo=mysql_fetch_array($ergebnis);
		print '
		<input type="radio" name="groupopt" value="'.$ginfo[article].'"> 
		<a href="#" onClick="document.selectform.groupopt['.$i.'].checked=true"> '.$ginfo[article].'</a><br>';
	}
	print '
  <p></td>
  </tr>
  <tr>
    <td >&nbsp;</td>
    <td colspan=2><FONT  SIZE=4 COLOR="#000066" FACE="verdana,Arial">oder...</td>
  </tr>
	';
}
 ?>

    <td>&nbsp;</td>
    <td bgcolor="ccffff" colspan=2><FONT FACE="verdana,Arial"><p><br>
		<input type="radio" name="groupopt" value="newgroup" <? if (!$rows) print "checked"; ?>> 
		<a href="#" <? if($rows) print 'onClick="document.selectform.groupopt['.$i.'].checked=true"';?>><?=$LDCreateGroup ?></a><br><p>
  </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td><p><br>
		<input type="button" value="<?=$LDBackBut ?>" onClick="window.history.back()">&nbsp;&nbsp;&nbsp;
        <input type="button" value="<?=$LDCancelBut ?>" onClick="window.location.replace('cafenews.php?sid=<?="$ck_sid&lang=$lang" ?>')"></td>
    <td align=right><p><br><FONT FACE="verdana,Arial">
		<input type="submit" value="<?=$LDContinueBut ?>">
  </td>
  </tr>
</table>
<input type="hidden" name="sid" value="<?=$ck_sid ?>">
<input type="hidden" name="lang" value="<?=$lang ?>">
</form></body>
</html>
