<?
if(!$lang)
	if(!$ck_language) include("../chklang.php");
		else $lang=$ck_language;
if (!$sid||($sid!=$ck_sid)) {header("Location:../language/".$lang."/lang_".$lang."_invalid-access-warning.php"); exit;}; 
require("../language/".$lang."/lang_".$lang."_nursing.php");
?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 14.10.01 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

</head>
<body><font size=5 face=arial color=maroon><?=$LDPreview ?><p>


<img src="../img/pixel.gif" border=0  name="preview">
<form name="picnotes">
<table border=0 cellspacing=0 cellpadding=0>
  <tr>
    <td><font size=2 face=arial color=maroon><?=$LDShotDate ?>:
</td>
    <td><input type="text" name="sdate" size=15 maxlength=15><div id="shotdate"></div></td>
  </tr>
  <tr>
    <td><font size=2 face=arial color=maroon><?=$LDShotNr ?>:</td>
    <td><input type="text" name="nr" size=2 maxlength=3><div id="snr"></div></td>
  </tr>
</table>
<textarea name="notes" cols=40 rows=4 wrap="physical">
</textarea><div id="notes"></div>
</form>
</body>
</html>
