<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 08.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>

</head>
<frameset cols="16%,*">
<?if($mode=="cont") : ?>
  <frame name="OPMINPUTFRAME" src="op-logbuch-container-input.php?sid=<?  print "$ck_sid&op_nr=$op_nr&patnum=$patnum&dept=$dept&saal=$saal&pday=$pday&pmonth=$pmonth&pyear=$pyear"; ?>">
  <frame name="OPMLISTFRAME" src="op-logbuch-container-list.php?sid=<?  print "$ck_sid&op_nr=$op_nr&patnum=$patnum&dept=$dept&saal=$saal&pday=$pday&pmonth=$pmonth&pyear=$pyear"; ?>">
<? else : ?>
  <frame name="OPMINPUTFRAME" src="op-logbuch-material-input.php?sid=<?  print "$ck_sid&op_nr=$op_nr&patnum=$patnum&dept=$dept&saal=$saal&pday=$pday&pmonth=$pmonth&pyear=$pyear"; ?>">
  <frame name="OPMLISTFRAME" src="op-logbuch-material-list.php?sid=<?  print "$ck_sid&op_nr=$op_nr&patnum=$patnum&dept=$dept&saal=$saal&pday=$pday&pmonth=$pmonth&pyear=$pyear"; ?>">
<? endif ?>
<noframes>
<body>


</body>
</noframes>
</frameset>
</html>
