<?php
//simulate plop dept
$dept="plop";
// set or create an order id number
if($oid!="") $order_id=str_replace($dept,"",$oid);
	else	$order_id=uniqid("");

?>
<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 16.07.01 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>
<meta name="Description" content="">
<meta name="Keywords" content="">
<meta name="Author" content="Lorilla Bong">
<meta name="Generator" content="AceHTML 4 Freeware">
</head>




<frameset rows="4%,*">
  <frame name="BHEADER" src="apotheke-bestell-hf.htm" scrolling="no" frameborder="yes" >
  <frameset cols="50%,*">
    <frame name="BESTELLKORB" src="apotheke-bestellkorb.php?sid=<?print "$ck_sid&dept=$dept&order_id=$order_id&itwassent=$itwassent"; ?>" scrolling="auto" frameborder="yes">
    <frame name="BESTELLKATALOG" src="apotheke-bestellkatalog.php?sid=<?print "$ck_sid&dept=$dept&order_id=$order_id"; ?>" scrolling="auto" frameborder="yes">
  </frameset>
<noframes>
</noframes>


<body>

</body>
</noframes>
</frameset>

</html>
