<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 08.12.2001 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title></title>

</head>
<frameset cols="16%,*">
  <frame name="OPMINPUTFRAME" src="op-material-input.php?sid=<?  print "$ck_sid&patnum=$patnum&dept=$dept&saal=$saal&pday=$pday&pmonth=$pmonth&pyear=$pyear"; ?>">
  <frame name="OPMLISTFRAME" src="op-material-list.php?sid=<?  print "$ck_sid&patnum=$patnum&dept=$dept&saal=$saal&pday=$pday&pmonth=$pmonth&pyear=$pyear"; ?>">
<noframes>
<body>


</body>
</noframes>
</frameset>
</html>
