<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
  <!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 25.12.2001 -->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="generator" content="HTML Tidy, see www.w3.org" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title></title>
</head>
<body alink="#0000ff" vlink="#0000ff" link="#0000ff">
<strong>Help</strong>
<p><a href="../include/help/help-info.php?lang=en" target="HELPINFOFRAME">Initial steps</a><br />
</p>

<p></p>

<p><strong><strong>*</strong><a href="http://care2x.org/wiki/index.php/UM_-_English" target="HELPINFOFRAME">Online Manual</a></strong></p>

<p><strong>*</strong><a href="http://care2x.org/wiki/index.php/Workflow_Charts" target="HELPINFOFRAME">Workflow charts</a> </p>

<p>(needs Internet connection<strong>*</strong>) </p>
</body>
</html>

